<?php
namespace App\Services;
use App\Models\AuditLog;
use App\Models\CmsPage;
use App\Models\CmsVersion;
use App\Models\User;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class CmsService
{
 public const TYPES=['hero','text','cta','stats','image_text'];
 private const CONTENT_KEYS=['hero'=>['eyebrow','eyebrow_marks','heading','heading_marks','text','text_marks','primary_label','primary_url','primary_action','primary_style','primary_icon','primary_icon_position','primary_target','primary_visibility','secondary_label','secondary_url','secondary_action','secondary_style','secondary_icon','secondary_icon_position','secondary_target','secondary_visibility'],'text'=>['eyebrow','eyebrow_marks','heading','heading_marks','body','body_marks'],'cta'=>['eyebrow','eyebrow_marks','heading','heading_marks','text','text_marks','button_label','button_url','button_action','button_style','button_icon','button_icon_position','button_target','button_visibility'],'stats'=>['eyebrow','eyebrow_marks','heading','heading_marks','text','text_marks','items'],'image_text'=>['eyebrow','eyebrow_marks','heading','heading_marks','text','text_marks','image_url','image_alt','image_link']];
 public function validateContent(string $type,array $content):array{
  if(!in_array($type,self::TYPES,true))throw ValidationException::withMessages(['type'=>'Choose a supported section type.']);$unknown=array_diff(array_keys($content),self::CONTENT_KEYS[$type]);if($unknown)throw ValidationException::withMessages(['content'=>'This section contains unsupported fields.']);
  foreach($content as $key=>$value){if($key==='items'){if(!is_array($value)||count($value)>8)throw ValidationException::withMessages(['content.items'=>'Statistics must contain no more than eight items.']);foreach($value as $item){if(!is_array($item)||array_diff(array_keys($item),['value','label'])||!isset($item['value'],$item['label']))throw ValidationException::withMessages(['content.items'=>'Each statistic needs a value and label.']);$this->plain($item['value'],40);$this->plain($item['label'],80);}continue;}if(str_ends_with($key,'_marks')){$this->marks($key,$value,$content);continue;}if(!is_string($value))throw ValidationException::withMessages(["content.{$key}"=>'Content must be text.']);if(str_ends_with($key,'_url')||$key==='image_link')$this->safeUrl($value);elseif(str_ends_with($key,'_action')&&!in_array($value,['internal','external','email','telephone'],true))throw ValidationException::withMessages(["content.{$key}"=>'Choose a supported action type.']);elseif(str_ends_with($key,'_style')&&!in_array($value,['primary','outline','light'],true))throw ValidationException::withMessages(["content.{$key}"=>'Choose a supported button style.']);elseif(str_ends_with($key,'_icon')&&!in_array($value,['none','arrow','calendar','external','mail','phone','heart'],true))throw ValidationException::withMessages(["content.{$key}"=>'Choose a supported button icon.']);elseif(str_ends_with($key,'_icon_position')&&!in_array($value,['left','right'],true))throw ValidationException::withMessages(["content.{$key}"=>'Choose a supported icon position.']);elseif(str_ends_with($key,'_target')&&!in_array($value,['_self','_blank'],true))throw ValidationException::withMessages(["content.{$key}"=>'Choose a safe target.']);elseif(str_ends_with($key,'_visibility')&&!in_array($value,['show','hide'],true))throw ValidationException::withMessages(["content.{$key}"=>'Choose whether the button is shown.']);else $this->plain($value,$key==='body'||$key==='text'?4000:200);}foreach(['primary','secondary','button']as$prefix)if(isset($content["{$prefix}_action"]))$this->actionUrl($content["{$prefix}_action"],$content["{$prefix}_url"]??'');
  if(empty($content['heading']))throw ValidationException::withMessages(['content.heading'=>'A heading is required.']);return $content;
 }
 public function validatePresentation(array $data):array{
  $allowed=['background'=>['ivory','white','wine','blush'],'alignment'=>['left','center'],'width'=>['normal','narrow','wide'],'spacing'=>['compact','normal','generous'],'font_family'=>['site','editorial','modern'],'font_size'=>['small','normal','large'],'font_weight'=>['regular','medium','bold'],'emphasis'=>['none','italic','underline','italic_underline'],'text_color'=>['default','wine','muted','white'],'line_height'=>['snug','normal','relaxed'],'image_width'=>['small','medium','large','full'],'image_alignment'=>['left','right'],'image_radius'=>['none','soft','round'],'image_fit'=>['cover','contain'],'crop_position'=>['top','center','bottom']];
  if(array_diff(array_keys($data),[...array_keys($allowed),'text_styles','button_styles']))throw ValidationException::withMessages(['presentation'=>'Unsupported presentation setting.']);
  foreach($data as$key=>$value){if($key==='text_styles'){$data[$key]=$this->textStyles($value);continue;}if($key==='button_styles'){$data[$key]=$this->buttonStyles($value);continue;}if(!in_array($value,$allowed[$key],true))throw ValidationException::withMessages(["presentation.{$key}"=>'Choose a supported option.']);}
  return$data;
 }
 public function snapshot(CmsPage $page):array{return['schema_version'=>3,'title'=>$page->title,'slug'=>$page->slug,'template'=>$page->template,'seo'=>['title'=>$page->seo_title,'description'=>$page->seo_description],'sections'=>$page->sections()->get()->map(fn($s)=>$s->only(['id','section_key','type','sort_order','is_visible','content','presentation']))->all()];}
 public function validateDocumentSections(CmsPage $page,array $sections):array{
  if(count($sections)>100)throw ValidationException::withMessages(['sections'=>'A page may contain no more than 100 sections.']);
  $ids=[];$keys=[];$known=$page->sections()->pluck('id')->map(fn($id)=>(int)$id)->all();$validated=[];
  foreach(array_values($sections) as$order=>$section){
   if(!is_array($section)||array_diff(array_keys($section),['id','section_key','type','sort_order','is_visible','content','presentation']))throw ValidationException::withMessages(["sections.{$order}"=>'This section has an invalid structured schema.']);
   $id=isset($section['id'])?(int)$section['id']:null;if($id&&(!in_array($id,$known,true)||in_array($id,$ids,true)))throw ValidationException::withMessages(["sections.{$order}.id"=>'This section does not belong to the page or appears more than once.']);if($id)$ids[]=$id;
   $key=(string)($section['section_key']??'');if($key===''&&!$id)$key=(string)Str::uuid();if(!Str::isUuid($key)||in_array($key,$keys,true))throw ValidationException::withMessages(["sections.{$order}.section_key"=>'Each section needs one unique structured identifier.']);$keys[]=$key;
   $type=(string)($section['type']??'');$content=$section['content']??null;$presentation=$section['presentation']??[];
   if(!is_array($content)||!is_array($presentation)||!is_bool($section['is_visible']??null))throw ValidationException::withMessages(["sections.{$order}"=>'Section content, presentation and visibility are required.']);
   $validated[]=['id'=>$id,'section_key'=>$key,'type'=>$type,'sort_order'=>$order,'is_visible'=>$section['is_visible'],'content'=>$this->validateContent($type,$content),'presentation'=>$this->validatePresentation($presentation)];
  }
  return$validated;
 }
 public function applyDocumentSections(CmsPage $page,array $sections):void{
  $kept=[];foreach($sections as$section){$id=$section['id'];$attributes=Arr::except($section,'id');if($id){$page->sections()->whereKey($id)->update($attributes);$kept[]=$id;}elseif($existing=$page->sections()->where('section_key',$section['section_key'])->first()){$existing->update($attributes);$kept[]=$existing->id;}else{$kept[]=$page->sections()->create($attributes)->id;}}
  $page->sections()->whereNotIn('id',$kept)->delete();
 }
 public function version(CmsPage $page,User $actor,string $reason):CmsVersion{$next=((int)$page->versions()->max('version'))+1;$version=$page->versions()->create(['version'=>$next,'reason'=>$reason,'snapshot'=>$this->snapshot($page),'created_by'=>$actor->id]);$this->audit($actor,'cms.version_created',$page,['version'=>$next,'reason'=>$reason]);return $version;}
 public function audit(User $actor,string $action,CmsPage $page,array $metadata=[]):void{AuditLog::create(['actor_id'=>$actor->id,'action'=>$action,'subject_type'=>CmsPage::class,'subject_id'=>$page->id,'metadata'=>$metadata]);}
 private function plain(string $value,int $max):void{if(mb_strlen($value)>$max||$value!==strip_tags($value))throw ValidationException::withMessages(['content'=>'Content must be plain text within the allowed length.']);}
 private function safeUrl(string $value):void{if($value===''||str_starts_with($value,'/'))return;if(str_starts_with($value,'mailto:')&&filter_var(substr($value,7),FILTER_VALIDATE_EMAIL))return;if(str_starts_with($value,'tel:')&&preg_match('/^tel:\+?[0-9 ()-]{7,30}$/',$value))return;if(!filter_var($value,FILTER_VALIDATE_URL)||!in_array(parse_url($value,PHP_URL_SCHEME),['https','http'],true))throw ValidationException::withMessages(['content'=>'Links must be an internal path, email, telephone, or safe HTTP(S) URL.']);}
 private function actionUrl(string $action,string $url):void{$valid=$action==='internal'&&str_starts_with($url,'/')||$action==='external'&&filter_var($url,FILTER_VALIDATE_URL)&&in_array(parse_url($url,PHP_URL_SCHEME),['https','http'],true)||$action==='email'&&str_starts_with($url,'mailto:')&&filter_var(substr($url,7),FILTER_VALIDATE_EMAIL)||$action==='telephone'&&preg_match('/^tel:\+?[0-9 ()-]{7,30}$/',$url);if(!$valid)throw ValidationException::withMessages(['content'=>'The selected action and destination do not match.']);}
 private function marks(string $key,mixed $marks,array $content):void{$field=substr($key,0,-6);$length=mb_strlen((string)($content[$field]??''));if(!is_array($marks)||count($marks)>30)throw ValidationException::withMessages(["content.{$key}"=>'Text formatting must be a short list of safe ranges.']);$lastEnd=0;foreach($marks as$mark){if(!is_array($mark)||array_diff(array_keys($mark),['type','start','end','url','target','action'])||!in_array($mark['type']??null,['bold','italic','underline','link'],true)||!is_int($mark['start']??null)||!is_int($mark['end']??null)||$mark['start']<$lastEnd||$mark['start']<0||$mark['end']<=$mark['start']||$mark['end']>$length)throw ValidationException::withMessages(["content.{$key}"=>'Text formatting ranges must be ordered, non-overlapping and inside the text.']);if($mark['type']==='link'){if(empty($mark['url']))throw ValidationException::withMessages(["content.{$key}"=>'A link formatting range needs a safe URL.']);$this->safeUrl((string)$mark['url']);if(isset($mark['target'])&&!in_array($mark['target'],['_self','_blank'],true))throw ValidationException::withMessages(["content.{$key}"=>'Choose a safe link target.']);if(isset($mark['action'])){if(!in_array($mark['action'],['internal','external','email','telephone'],true))throw ValidationException::withMessages(["content.{$key}"=>'Choose a supported link action.']);$this->actionUrl($mark['action'],$mark['url']);}}elseif(isset($mark['url'])||isset($mark['target'])||isset($mark['action']))throw ValidationException::withMessages(["content.{$key}"=>'Only link formatting accepts a URL, target and action.']);$lastEnd=$mark['end'];}}
 private function textStyles(mixed $styles):array{
  if(!is_array($styles)||count($styles)>30)throw ValidationException::withMessages(['presentation.text_styles'=>'Text styles must be a short structured map.']);$fields=['eyebrow','heading','text','body','label','caption','primary_label','secondary_label','button_label'];$allowed=['font_family'=>['site','editorial','modern'],'font_size'=>['xs','sm','base','lg','xl','2xl','3xl','4xl','5xl'],'font_weight'=>['400','500','600','700','800'],'bold'=>[true,false],'italic'=>[true,false],'underline'=>[true,false],'color'=>['default','wine','muted','white','black'],'alignment'=>['left','center','right','justify'],'line_height'=>['1','1.2','1.4','1.6','1.8','2'],'letter_spacing'=>['-0.04em','-0.02em','0','0.02em','0.05em','0.1em'],'text_decoration'=>['none','underline','line-through','overline']];foreach($styles as$field=>$style){if(!in_array($field,$fields,true)||!is_array($style)||array_diff(array_keys($style),array_keys($allowed)))throw ValidationException::withMessages(["presentation.text_styles.{$field}"=>'This text element contains unsupported styles.']);foreach($style as$key=>$value)if(!in_array($value,$allowed[$key],true))throw ValidationException::withMessages(["presentation.text_styles.{$field}.{$key}"=>'Choose an approved text style value.']);}return$styles;
 }
 private function buttonStyles(mixed $styles):array{
  if(!is_array($styles)||count($styles)>3)throw ValidationException::withMessages(['presentation.button_styles'=>'Button styles must be a short structured map.']);$fields=['primary','secondary','button'];$allowed=['alignment'=>['left','center','right'],'size'=>['small','normal','large'],'font_family'=>['site','editorial','modern'],'font_size'=>['sm','base','lg','xl','2xl'],'font_weight'=>['400','500','600','700','800'],'background_color'=>['primary','wine','white','transparent','blush','black'],'text_color'=>['white','wine','black'],'border_style'=>['none','solid','dashed'],'border_width'=>['0','1','2','3'],'border_color'=>['transparent','wine','white','black','rose'],'border_radius'=>['0','6','12','24','999'],'padding_x'=>['8','12','16','20','24','32'],'padding_y'=>['6','8','10','12','16','20'],'margin'=>['0','4','8','12','16','24']];foreach($styles as$field=>$style){if(!in_array($field,$fields,true)||!is_array($style)||array_diff(array_keys($style),array_keys($allowed)))throw ValidationException::withMessages(["presentation.button_styles.{$field}"=>'This button contains unsupported styles.']);foreach($style as$key=>$value)if(!in_array($value,$allowed[$key],true))throw ValidationException::withMessages(["presentation.button_styles.{$field}.{$key}"=>'Choose an approved button style value.']);}return$styles;
 }
}
