import type { Appointment,AvailabilitySlot,DataEnvelope } from '@dr-funmilola/mobile-contract';
import { useMutation } from '@tanstack/react-query';
import { useState } from 'react';
import { Alert,RefreshControl,StyleSheet,Text,View } from 'react-native';
import { apiRequest,ApiClientError } from '@/lib/api';
import { Button,Card,Empty,Field,Heading,Loading,Notice,Screen,text } from '@/components/ui';
import { usePatientPage } from '@/hooks/usePatientPage';
import { useSession } from '@/providers/SessionProvider';
import { queryClient } from '@/providers/queryClient';
import { colors,spacing } from '@/theme';
import { createMutationId } from '@/lib/mutation';

export default function Appointments(){
  const {session}=useSession();
  const query=usePatientPage<Appointment>('appointments','/appointments?per_page=50');
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[open,setOpen]=useState<number|null>(null),[date,setDate]=useState(''),[slots,setSlots]=useState<AvailabilitySlot[]>([]),[selected,setSelected]=useState(''),[loadingSlots,setLoadingSlots]=useState(false);
  const fail=(e:unknown)=>setError(e instanceof ApiClientError?e.message:'The request could not be sent.');
  const refresh=async()=>{await queryClient.invalidateQueries({queryKey:['appointments']})};
  const cancel=useMutation({mutationFn:(appointment:Appointment)=>apiRequest<DataEnvelope<{id:number;status:string}>>(`/appointments/${appointment.id}/cancellation-requests`,{method:'POST',token:session!.token,body:{client_request_id:createMutationId()}}),onSuccess:async()=>{setError('');setMessage('Cancellation request sent for practice review.');await refresh()},onError:fail});
  const reschedule=useMutation({mutationFn:({appointment,startsAt}:{appointment:Appointment;startsAt:string})=>apiRequest<DataEnvelope<{id:number;status:string}>>(`/appointments/${appointment.id}/reschedule-requests`,{method:'POST',token:session!.token,body:{client_request_id:createMutationId(),starts_at:startsAt}}),onSuccess:async()=>{setOpen(null);setDate('');setSlots([]);setSelected('');setError('');setMessage('Preferred time sent for practice approval.');await refresh()},onError:fail});
  function confirm(a:Appointment){Alert.alert('Request cancellation?',`The practice will review the request for ${new Date(a.starts_at).toLocaleString()}.`,[{text:'Keep appointment',style:'cancel'},{text:'Send request',style:'destructive',onPress:()=>cancel.mutate(a)}]);}
  async function findTimes(a:Appointment){setLoadingSlots(true);setError('');setSlots([]);setSelected('');try{const result=await apiRequest<DataEnvelope<AvailabilitySlot[]>>(`/appointments/${a.id}/reschedule-options?date=${encodeURIComponent(date)}`,{token:session!.token});setSlots(result.data)}catch(e){fail(e)}finally{setLoadingSlots(false)}}
  const requestStatus=(a:Appointment)=>a.reschedule_request?.status==='pending'?'Reschedule requested':a.cancellation_request?.status==='pending'?'Cancellation requested':a.reschedule_request?.status==='declined'?'Reschedule declined':a.cancellation_request?.status==='declined'?'Cancellation declined':null;
  return <Screen refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={()=>void query.refetch()} tintColor={colors.green}/>}><Heading title="Appointments" body="Actions shown here come from the practice server and update after every review."/>{error?<Notice tone="error" title="Request not sent" body={error}/>:null}{message?<Notice title="Request received" body={message}/>:null}{query.isLoading?<Loading/>:query.isError?<Notice tone="error" title="Appointments unavailable" body="Pull down to try again."/>:query.data?.data.length===0?<Empty title="No appointments yet" body="Your requested and confirmed appointments will appear here."/>:query.data?.data.map(a=><Card key={a.public_id} label={`${a.service.name} appointment`}><Text style={text.badge}>{a.status.replaceAll('_',' ')}</Text><Text style={text.title}>{a.service.name}</Text><Text style={text.body}>{new Date(a.starts_at).toLocaleString()}</Text><Text style={text.muted}>{a.consultation_method==='online'?'Online consultation':a.location??'Practice location shared after confirmation'}</Text>{requestStatus(a)?<Text style={styles.request}>{requestStatus(a)}</Text>:null}{a.allowed_actions.includes('request_reschedule')?<Button title="Request a new time" variant="secondary" onPress={()=>{setOpen(open===a.id?null:a.id);setDate('');setSlots([]);setSelected('')}}/>:null}{open===a.id?<View style={styles.change}><Field label="Preferred date (YYYY-MM-DD)" value={date} onChangeText={setDate} placeholder="2026-09-14" autoCapitalize="none"/><Button title={loadingSlots?'Finding times…':'Find available times'} variant="secondary" disabled={loadingSlots||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(date)} onPress={()=>void findTimes(a)}/>{!loadingSlots&&date&&slots.length===0?<Text style={text.muted}>No times loaded for this date. Try another date.</Text>:null}{slots.map(slot=><Button key={slot.starts_at} title={`${selected===slot.starts_at?'Selected: ':''}${slot.label}`} variant={selected===slot.starts_at?'primary':'secondary'} onPress={()=>setSelected(slot.starts_at)}/>) }<Button title={reschedule.isPending?'Sending…':'Request selected time'} disabled={!selected||reschedule.isPending} onPress={()=>reschedule.mutate({appointment:a,startsAt:selected})}/></View>:null}{a.allowed_actions.includes('request_cancellation')?<Button title={cancel.isPending?'Sending…':'Request cancellation'} variant="danger" disabled={cancel.isPending} onPress={()=>confirm(a)}/>:null}</Card>)}</Screen>;
}

const styles=StyleSheet.create({request:{color:colors.greenDark,fontWeight:'700'},change:{gap:spacing.sm,paddingTop:spacing.xs}});
