import { useQuery } from '@tanstack/react-query';
import { useEffect, useRef, useState } from 'react';
import { Routes, Route, Link, useLocation } from 'react-router-dom';
import { ArrowRight, CalendarDays, HeartPulse, Menu, Microscope, ShieldCheck, Stethoscope, Video, BookOpen, MapPin, Pencil, X, MousePointer2, Plus, Undo2, Redo2, Eye, Save, Send } from 'lucide-react';
import type { PublicData } from './types';
import BookingPage from './pages/BookingPage';
import { ForgotPasswordPage, RegisterPage, ResetPasswordPage, SignInPage } from './pages/AuthPage';
import PortalPage from './pages/PortalPage';
import StaffDashboardPage from './pages/StaffDashboardPage';
import StaffInboxPage from './pages/StaffInboxPage';
import StaffCalendarPage from './pages/StaffCalendarPage';
import ReminderPreferencesPage from './pages/ReminderPreferencesPage';
import ConsultationsPage from './pages/ConsultationsPage';
import StaffConsultationsPage from './pages/StaffConsultationsPage';
import CmsPublicPage from './pages/CmsPublicPage';
import CmsEditorPage from './pages/CmsEditorPage';
import VerificationQueuePage from './pages/VerificationQueuePage';
import AcademicPortfolioPage from './pages/AcademicPortfolioPage';
import EducationPage from './pages/EducationPage';
import EducationManagerPage from './pages/EducationManagerPage';
import AuditLogPage from './pages/AuditLogPage';
import StaffAccountsPage from './pages/StaffAccountsPage';
import AccountSecurityPage from './pages/AccountSecurityPage';
import { api } from './api';
import { CmsEditContext, type CmsEditorBridge } from './CmsEditContext';
import Seo from './Seo';
import VisualNavigation from './VisualNavigation';
import { ContactPage, EducationArticlePage, LegalStatusPage, NotFoundPage, PublicationDetailPage, ServicesDirectory, VerifiedProfile } from './pages/PublicPages';

const getPublic = async (): Promise<PublicData> => { const r = await fetch('/api/public'); if (!r.ok) throw new Error('Unable to load practice information'); return r.json(); };
const DEFAULT_NAVIGATION=[{label:'Home',path:'/'},{label:'About',path:'/about'},{label:'Services',path:'/services'},{label:'Research',path:'/research',children:[{label:'Academic portfolio',path:'/academic'},{label:'Patient education',path:'/education'}]},{label:'Contact',path:'/contact'},{label:'Patient portal',path:'/portal'},{label:'Book appointment',path:'/book'}];

export function Layout({ children }: { children: React.ReactNode }) {
  const location=useLocation(),[editing,setEditing]=useState(false),[menuOpen,setMenuOpen]=useState(false),[editor,setEditor]=useState<CmsEditorBridge|null>(null),[navigationDirty,setNavigationDirty]=useState(false);
  const menuToggle=useRef<HTMLButtonElement>(null),main=useRef<HTMLElement>(null),previousPath=useRef(location.pathname);
  const me=useQuery({queryKey:['me'],queryFn:async()=>(await api.get('/me')).data.user,retry:false});
  const publicSettings=useQuery({queryKey:['cms-public-settings'],queryFn:async()=>(await api.get('/cms/public-settings')).data.data,retry:false,staleTime:60_000});
  const power=me.data?.role==='power_admin';
  const navigation=Array.isArray(publicSettings.data?.navigation)&&publicSettings.data.navigation.length?publicSettings.data.navigation:DEFAULT_NAVIGATION;
  const theme=publicSettings.data?.theme??{palette:'wine',density:'comfortable',heading_style:'editorial'};
  const coreSlug=location.pathname==='/'?'home':['about','services','research'].includes(location.pathname.slice(1))?location.pathname.slice(1):location.pathname.startsWith('/p/')?location.pathname.slice(3):'';
  const contextual=location.pathname.startsWith('/academic')?'/staff/research-review':location.pathname.startsWith('/education')?'/staff/education':coreSlug?`/staff/cms?slug=${encodeURIComponent(coreSlug)}`:'/staff/cms';
  useEffect(()=>{setMenuOpen(false);if(previousPath.current!==location.pathname){previousPath.current=location.pathname;main.current?.focus({preventScroll:true})}},[location.pathname]);
  useEffect(()=>{if(!menuOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenuOpen(false);menuToggle.current?.focus()}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[menuOpen]);
  useEffect(()=>{if(!power)setEditing(false)},[power]);
  const exitEditing=()=>{if(navigationDirty||editor?.saveState==='unsaved'||editor?.saveState==='failed'){if(!window.confirm('You have unsaved website changes. Exit Edit Mode and keep them only in this browser session?'))return}setEditing(false)};
  return <CmsEditContext.Provider value={{editing:Boolean(power&&editing),setEditing,editor,registerEditor:setEditor}}><div className={`site-shell theme-${theme.palette||'wine'} density-${theme.density||'comfortable'} headings-${theme.heading_style||'editorial'} ${editing?'site-editing':''}`}><a className="skip-link" href="#main-content">Skip to main content</a><header className="site-header"><nav className="navbar navbar-expand-lg" aria-label="Main navigation"><div className="container">
    <Link className="brand" to="/"><span className="brand-mark" aria-hidden="true"><HeartPulse size={22}/></span><span><b>Dr. Funmilola Wuraola</b><small>Breast Oncology Practice</small></span></Link>
    <button ref={menuToggle} type="button" className="navbar-toggler" aria-controls="main-navigation-links" aria-expanded={menuOpen} aria-label={menuOpen?'Close navigation':'Open navigation'} onClick={()=>setMenuOpen(open=>!open)}>{menuOpen?<X/>:<Menu/>}</button>
    <VisualNavigation published={navigation} editing={Boolean(power&&editing)} menuOpen={menuOpen} onDirty={setNavigationDirty}/></div></nav></header>{power&&!editing&&<button type="button" className="power-edit-entry" onClick={()=>setEditing(true)}><Pencil/> Edit site</button>}{power&&editing&&<div className="visual-editor-toolbar" role="toolbar" aria-label="Website editor"><div className="visual-editor-identity"><b>Edit Mode</b><span>{editor?.pageTitle||'This public page'}{editor?.selection?` · ${editor.selection}`:''}</span></div><button type="button" onClick={editor?.select} disabled={!editor}><MousePointer2/> Select</button><button type="button" onClick={editor?.addSection} disabled={!editor}><Plus/> Add Section</button><span className="visual-toolbar-separator"/><button type="button" onClick={editor?.undo} disabled={!editor?.canUndo}><Undo2/> Undo</button><button type="button" onClick={editor?.redo} disabled={!editor?.canRedo}><Redo2/> Redo</button><button type="button" onClick={editor?.preview} disabled={!editor}><Eye/> Preview</button><button type="button" onClick={editor?.save} disabled={!editor||editor.saveState==='saving'}><Save/> Save Draft</button><button type="button" className="publish" onClick={editor?.publish} disabled={!editor||editor.saveState==='saving'}><Send/> Publish</button><button type="button" onClick={exitEditing}><X/> Exit Edit Mode</button><span className={`visual-save-state ${navigationDirty?'unsaved':editor?.saveState||'clean'}`} role="status" aria-live="polite">{navigationDirty?'Unsaved navigation changes':!editor?'This page is not editable':editor.saveState==='unsaved'?'Unsaved changes':editor.saveState==='saving'?'Saving…':editor.saveState==='saved'?'Draft saved':editor.saveState==='failed'?'Save failed — changes retained':'All changes saved'}</span><Link className="visual-editor-more" to={contextual}>Page settings</Link></div>}<main ref={main} id="main-content" tabIndex={-1}>{children}</main><Footer/></div></CmsEditContext.Provider>;
}

function Footer() { return <footer><div className="container"><div className="row g-4"><div className="col-lg-5"><div className="footer-brand">Dr. Funmilola Wuraola</div><p>Specialist, evidence-informed breast care delivered with clarity, dignity and compassion.</p><p className="medical-note">Website information is educational and does not replace an individual medical consultation.</p></div><div className="col-6 col-lg-3"><h3>Practice</h3><Link to="/services">Services</Link><Link to="/book">Appointments</Link><Link to="/academic">Academic portfolio</Link><Link to="/education">Education</Link><Link to="/contact">Contact</Link></div><div className="col-6 col-lg-4"><h3>Location</h3><p><MapPin size={16}/> Ile-Ife, Osun State, Nigeria</p><p>Exact clinic details are shared with confirmed patients.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Dr. Funmilola Olanike Wuraola</span><nav aria-label="Legal information"><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/accessibility">Accessibility</Link></nav></div></div></footer>; }

function Home({ data }: { data?: PublicData }) { const services = data?.services ?? []; return <>
  <section className="hero"><div className="contour contour-one"/><div className="container"><div className="row align-items-center g-5"><div className="col-lg-7 hero-copy"><span className="eyebrow">Specialist breast care · Ile-Ife, Nigeria</span><h1>Care that sees the <em>whole woman,</em> not only the diagnosis.</h1><p className="lead">Specialist breast oncology and surgical care, grounded in evidence and shaped around each patient’s questions, priorities and life.</p><div className="hero-actions"><Link className="btn btn-primary btn-lg" to="/book">Book an appointment <ArrowRight size={18}/></Link><Link className="btn btn-outline-primary btn-lg" to="/about">Meet Dr. Funmilola</Link></div><div className="trust-row"><span><ShieldCheck/> Confidential care</span><span><Microscope/> Evidence informed</span><span><HeartPulse/> Patient centred</span></div></div><div className="col-lg-5"><div className="portrait-card" role="img" aria-label="Professional portrait placeholder pending approved photography"><div className="portrait-art"><span>FW</span></div><div className="portrait-caption"><b>Dr. Funmilola Olanike Wuraola</b><small>Breast Oncology Surgeon & Academic Clinician</small></div></div></div></div></div></section>
  <section className="intro-strip"><div className="container"><div><span>Breast health deserves</span><strong>specialist attention, thoughtful explanation, and a clear plan.</strong></div><Link to="/book">Start your care journey <ArrowRight/></Link></div></section>
  <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">Specialist focus</span><h2>Focused expertise. Personal care.</h2><p>From a new breast concern to cancer treatment and follow-up, each step begins with listening.</p></div><div className="row g-4">{services.slice(0,6).map((s,i)=><div className="col-md-6 col-lg-4" key={s.id}><article className="service-card"><span className="service-number">0{i+1}</span><div className="service-icon">{i%3===0?<Stethoscope/>:i%3===1?<HeartPulse/>:<Microscope/>}</div><h3>{s.name}</h3><p>{s.summary}</p><Link to="/book">Request consultation <ArrowRight/></Link></article></div>)}</div></div></section>
  <section className="section why"><div className="container"><div className="row g-5 align-items-center"><div className="col-lg-5"><span className="eyebrow">A considered approach</span><h2>Serious expertise can still feel human.</h2><p className="lead-sm">Breast concerns often arrive with uncertainty. Our practice is designed to replace that uncertainty with careful assessment, understandable choices and a coordinated next step.</p><Link to="/about" className="text-link">About the practice <ArrowRight/></Link></div><div className="col-lg-7"><div className="principles"><div><b>01</b><h3>Listen first</h3><p>Your concerns, values and questions guide the conversation.</p></div><div><b>02</b><h3>Explain clearly</h3><p>Complex medical information translated into an understandable plan.</p></div><div><b>03</b><h3>Decide together</h3><p>Evidence-based options considered around the person receiving care.</p></div><div><b>04</b><h3>Stay connected</h3><p>A clear follow-up path through appointments and consultation.</p></div></div></div></div></div></section>
  <section className="section research-preview"><div className="container"><div className="row g-5"><div className="col-lg-5"><span className="eyebrow light">Academic practice</span><h2>Care informed by research.</h2><p>Clinical practice and academic inquiry meet in a commitment to improving breast cancer care in Nigeria and across Africa.</p><Link to="/research" className="btn btn-light">Explore research <BookOpen size={18}/></Link></div><div className="col-lg-7"><div className="publication-panel"><span>Research profile</span><h3>Breast oncology, surgical care, screening, survivorship and equitable access.</h3><p>Publications shown publicly are released only after source verification. ORCID: {data?.profile.orcid}</p></div></div></div></div></section>
  <section className="cta"><div className="container"><CalendarDays/><div><span>Ready when you are</span><h2>Take the next step with confidence.</h2></div><Link className="btn btn-light btn-lg" to="/book">Request an appointment</Link></div></section>
  </>; }

function About() { return <PageHero eyebrow="About" title="A specialist practice built around clarity and compassion." intro="Dr. Funmilola Olanike Wuraola is a surgeon and academic clinician associated with Obafemi Awolowo University and OAUTHC in Ile-Ife, Nigeria." ><div className="notice"><ShieldCheck/><div><b>Profile verification in progress</b><p>Qualifications, appointments, fellowships and achievements will be published only after approval against authoritative sources.</p></div></div><ContentColumns/></PageHero>; }
function Services({ data }: { data?: PublicData }) { return <PageHero eyebrow="Clinical services" title="Breast care for the questions that cannot wait." intro="Choose the consultation that best matches your concern. The practice team will review every request and guide you if a different service is more appropriate."><div className="row g-4">{data?.services.map(s=><div className="col-md-6" key={s.id}><div className="service-card tall"><HeartPulse/><h3>{s.name}</h3><p>{s.description || s.summary}</p><p className="meta">Typical consultation · {s.duration_minutes} minutes {s.online_available && '· Online available'}</p><Link to="/book">Request this service <ArrowRight/></Link></div></div>)}</div></PageHero>; }
function Research({ data }: { data?: PublicData }) { return <PageHero eyebrow="Research & academic work" title="Improving breast cancer care through inquiry and collaboration." intro="This portfolio uses a verification-first publishing process. Draft research records stay private until a Power Admin approves their sources.">{data?.publications.length ? data.publications.map(p=><article className="publication" key={p.id}><span>{p.category}</span><h3>{p.title}</h3><p>{p.authors}</p><small>{p.journal} {p.published_at && `· ${new Date(p.published_at).getFullYear()}`}</small></article>) : <div className="empty-state"><BookOpen/><h3>Publication review is underway</h3><p>Seed records are held in the Research & Verification Queue until their bibliographic details are approved.</p></div>}</PageHero>; }
function PageHero({eyebrow,title,intro,children}:{eyebrow:string;title:string;intro:string;children:React.ReactNode}) { return <><section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></div></section><section className="section"><div className="container narrow">{children}</div></section></>; }
function ContentColumns(){return <div className="row g-5 mt-2"><div className="col-md-6"><h2>Professional profile</h2><p>Lecturer and Consultant General Surgeon. Further biography, education, specialist training and current appointments are pending verification before public release.</p></div><div className="col-md-6"><h2>Areas of inquiry</h2><p>Available seed material indicates work across breast cancer care, breast surgery, screening, genetics, survivorship and health systems. Each claim remains subject to source review.</p></div></div>}

export default function App(){
 const {data}=useQuery({queryKey:['public'],queryFn:getPublic});
 return <><DefaultRouteSeo/><Routes>
  <Route path="/sign-in" element={<SignInPage/>}/><Route path="/register" element={<RegisterPage/>}/><Route path="/forgot-password" element={<ForgotPasswordPage/>}/><Route path="/reset-password" element={<ResetPasswordPage/>}/>
  <Route path="/staff" element={<StaffDashboardPage/>}/><Route path="/staff/inbox" element={<StaffInboxPage/>}/><Route path="/staff/calendar" element={<StaffCalendarPage/>}/><Route path="/staff/consultations" element={<StaffConsultationsPage/>}/><Route path="/staff/accounts" element={<StaffAccountsPage/>}/><Route path="/staff/cms" element={<CmsEditorPage/>}/><Route path="/staff/research-review" element={<VerificationQueuePage/>}/><Route path="/staff/education" element={<EducationManagerPage/>}/><Route path="/staff/audit" element={<AuditLogPage/>}/><Route path="/security" element={<AccountSecurityPage/>}/><Route path="/preview/:token" element={<CmsPublicPage preview/>}/>
  <Route path="*" element={<Layout><Routes><Route path="/" element={<CmsPublicPage slug="home" fallback={<Home data={data}/>}/>}/><Route path="/about" element={<CmsPublicPage slug="about" fallback={<About/>} supplement={<VerifiedProfile/>}/>}/><Route path="/services" element={<CmsPublicPage slug="services" fallback={<Services data={data}/>} supplement={<ServicesDirectory data={data}/>}/>}/><Route path="/research" element={<CmsPublicPage slug="research" fallback={<Research data={data}/>}/>}/><Route path="/academic" element={<AcademicPortfolioPage/>}/><Route path="/academic/publications/:publicationId" element={<PublicationDetailPage/>}/><Route path="/education" element={<EducationPage/>}/><Route path="/education/:slug" element={<EducationArticlePage/>}/><Route path="/contact" element={<ContactPage/>}/><Route path="/privacy" element={<LegalStatusPage type="privacy"/>}/><Route path="/terms" element={<LegalStatusPage type="terms"/>}/><Route path="/accessibility" element={<LegalStatusPage type="accessibility"/>}/><Route path="/book" element={<BookingPage services={data?.services??[]}/>}/><Route path="/portal" element={<PortalPage/>}/><Route path="/portal/reminders" element={<ReminderPreferencesPage/>}/><Route path="/portal/consultations" element={<ConsultationsPage/>}/><Route path="/p/:slug" element={<CmsPublicPage/>}/><Route path="*" element={<NotFoundPage/>}/></Routes></Layout>}/>
 </Routes></>;
}

function DefaultRouteSeo(){const {pathname}=useLocation();const noIndex=/^\/(staff|portal|sign-in|register|forgot-password|reset-password|preview)(\/|$)/.test(pathname);const metadata:Record<string,[string,string]>={'/book':['Book an appointment','Request a breast oncology consultation using current practice availability.'],'/contact':['Contact the practice','Request an appointment or use secure patient portal messaging.'],'/':['Breast oncology care in Ile-Ife','Specialist breast oncology and breast surgery care in Ile-Ife, Nigeria.']};const [title,description]=metadata[pathname]??['Dr. Funmilola Olanike Wuraola','Specialist breast oncology care, academic work and patient education.'];return <Seo title={title} description={description} noIndex={noIndex}/>}
