import { useQuery,useQueryClient } from '@tanstack/react-query';
import { ArrowDown,ArrowUp,Eye,EyeOff,GripVertical,Plus,Save,Send,Trash2,X } from 'lucide-react';
import { useEffect,useId,useRef,useState } from 'react';
import { Link,NavLink,useLocation } from 'react-router-dom';
import { api } from './api';

export type NavigationItem={key:string;label:string;type:'internal'|'external';path:string;target:'_self'|'_blank';is_visible:boolean;children:NavigationItem[]};

const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const newKey=()=>crypto.randomUUID();
function normalize(items:any[]):NavigationItem[]{return items.map(item=>({key:uuidPattern.test(String(item?.key||''))?item.key:newKey(),label:String(item?.label||'Untitled link'),type:item?.type==='external'||/^https?:\/\//i.test(String(item?.path||''))?'external':'internal',path:String(item?.path||'/'),target:item?.target==='_blank'?'_blank':'_self',is_visible:item?.is_visible!==false,children:Array.isArray(item?.children)?normalize(item.children):[]}))}
function blankItem(label='New link'):NavigationItem{return{key:newKey(),label,type:'internal',path:'/',target:'_self',is_visible:true,children:[]}}

export default function VisualNavigation({published,editing,menuOpen,onDirty}:{published:any[];editing:boolean;menuOpen:boolean;onDirty:(dirty:boolean)=>void}){
 const location=useLocation(),qc=useQueryClient(),[draft,setDraft]=useState<NavigationItem[]>(()=>normalize(published)),[selected,setSelected]=useState<string|null>(null),[state,setState]=useState<'clean'|'unsaved'|'saving'|'saved'|'failed'>('clean'),[message,setMessage]=useState(''),[error,setError]=useState('');
 const settings=useQuery({queryKey:['cms-settings'],queryFn:async()=>(await api.get('/cms/settings')).data.data,enabled:editing,retry:false});
 useEffect(()=>{if(!editing){setSelected(null);setState('clean');onDirty(false);return}if(settings.data!==undefined){const source=settings.data?.navigation?.draft_value??settings.data?.navigation?.published_value??published;setDraft(normalize(Array.isArray(source)?source:published));setState('clean');setError('');onDirty(false)}},[editing,settings.data]);
 useEffect(()=>{if(!editing)setDraft(normalize(published))},[editing,published]);
 useEffect(()=>{if(!editing||!['unsaved','failed'].includes(state))return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[editing,state]);
 const changed=(next:NavigationItem[])=>{setDraft(next);setState('unsaved');setMessage('Navigation changed in this private browser draft.');setError('');onDirty(true)};
 const selectedLocation=locate(draft,selected),selectedItem=selectedLocation?.item;
 const update=(change:(item:NavigationItem)=>NavigationItem)=>{if(!selected)return;changed(draft.map(root=>root.key===selected?change(root):{...root,children:root.children.map(child=>child.key===selected?change(child):child)}))};
 const addRoot=()=>{if(draft.length>=8){setError('Navigation already has the maximum of eight main links.');return}const item=blankItem();changed([...draft,item]);setSelected(item.key)};
 const addChild=()=>{if(!selectedLocation||selectedLocation.parentKey||selectedLocation.item.children.length>=6)return;const child=blankItem('New submenu link');changed(draft.map(root=>root.key===selected?{...root,children:[...root.children,child]}:root));setSelected(child.key)};
 const move=(direction:-1|1)=>{if(!selectedLocation)return;const list=selectedLocation.parentKey?draft.find(root=>root.key===selectedLocation.parentKey)?.children:draft;if(!list)return;const from=list.findIndex(item=>item.key===selected),to=from+direction;if(from<0||to<0||to>=list.length)return;const reordered=[...list],[item]=reordered.splice(from,1);reordered.splice(to,0,item);changed(selectedLocation.parentKey?draft.map(root=>root.key===selectedLocation.parentKey?{...root,children:reordered}:root):reordered)};
 const remove=()=>{if(!selectedLocation||!window.confirm(`Delete “${selectedLocation.item.label}” from the private navigation draft?`))return;changed(selectedLocation.parentKey?draft.map(root=>root.key===selectedLocation.parentKey?{...root,children:root.children.filter(child=>child.key!==selected)}:root):draft.filter(root=>root.key!==selected));setSelected(selectedLocation.parentKey)};
 const drop=(source:string,target:string)=>{if(source===target)return;const from=draft.findIndex(item=>item.key===source),to=draft.findIndex(item=>item.key===target);if(from<0||to<0)return;const next=[...draft],[item]=next.splice(from,1);next.splice(to,0,item);changed(next);setSelected(source)};
 const save=async()=>{setState('saving');setError('');try{const response=await api.put('/cms/settings/navigation',{value:draft}),clean=normalize(response.data.data.draft_value);setDraft(clean);setState('saved');setMessage('Navigation draft saved privately. Logged-out visitors still see the published navigation.');onDirty(false);return clean}catch(e:any){setState('failed');setError(e?.response?.data?.message||'Navigation could not be saved. Your changes are retained here.');onDirty(true);return null}};
 const publish=async()=>{if(!window.confirm('Publish this exact navigation for all website visitors?'))return;const clean=await save();if(!clean)return;setState('saving');try{await api.post('/cms/settings/navigation/publish');setState('saved');setMessage('Navigation published. Logged-out visitors now receive this exact header.');await qc.invalidateQueries({queryKey:['cms-public-settings']})}catch(e:any){setState('failed');setError(e?.response?.data?.message||'Navigation publication failed. The previous public header remains live.')}};
 const visible=editing?draft:normalize(published).filter(item=>item.is_visible);
 return <>
  <div id="main-navigation-links" className={`collapse navbar-collapse justify-content-end ${menuOpen?'show':''}`}><div className={`navbar-nav align-items-lg-center gap-lg-2 ${editing?'cms-rendered-nav-editing':''}`}>
   {visible.map(item=><div className={`${editing?'cms-nav-edit-item':''} ${item.is_visible?'':'cms-nav-item-hidden'} ${selected===item.key?'selected':''}`} onDragOver={event=>editing&&event.preventDefault()} onDrop={event=>{if(!editing)return;event.preventDefault();drop(event.dataTransfer.getData('text/cms-navigation'),item.key)}} key={item.key}>
    {editing&&<button type="button" className="cms-nav-drag" draggable aria-label={`Drag ${item.label} navigation item to reorder`} onDragStart={event=>{event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/cms-navigation',item.key)}}><GripVertical/></button>}
    <NavigationEntry item={item} editing={editing} selected={selected} onSelect={setSelected}/>
   </div>)}
   {editing&&<button type="button" className="cms-select-navigation" aria-expanded={Boolean(selected)} onClick={()=>setSelected('navigation')}><span>Edit rendered navigation</span></button>}
  </div></div>
  {editing&&selected&&<aside className="cms-navigation-inspector" aria-label="Rendered navigation controls"><header><div><span>Selected on actual page</span><b>{selectedItem?`Navigation › ${selectedLocation?.parentKey?'Submenu › ':''}${selectedItem.label}`:'Navigation'}</b></div><button type="button" aria-label="Close navigation controls" onClick={()=>setSelected(null)}><X/></button></header>
   {!selectedItem?<><p>Select any rendered link to edit it, including links shown here only because they are hidden from visitors.</p><button type="button" className="btn btn-outline-primary" disabled={draft.length>=8} onClick={addRoot}><Plus/> Add main navigation item</button></>:<><div className="cms-inspector-grid"><label>Navigation label<input value={selectedItem.label} maxLength={40} onChange={event=>update(item=>({...item,label:event.target.value}))}/></label><label>Destination type<select value={selectedItem.type} onChange={event=>update(item=>({...item,type:event.target.value as NavigationItem['type'],path:''}))}><option value="internal">Internal page or route</option><option value="external">External website</option></select></label><label>Navigation destination<input value={selectedItem.path} placeholder={selectedItem.type==='internal'?'/about':'https://example.org'} onChange={event=>update(item=>({...item,path:event.target.value}))}/></label><label>Open link<select value={selectedItem.target} onChange={event=>update(item=>({...item,target:event.target.value as NavigationItem['target']}))}><option value="_self">Same tab</option><option value="_blank">New tab</option></select></label><label className="cms-navigation-visible"><input type="checkbox" checked={selectedItem.is_visible} onChange={event=>update(item=>({...item,is_visible:event.target.checked}))}/> Show this item to visitors</label></div><div className="cms-navigation-actions"><button type="button" onClick={()=>move(-1)} disabled={!selectedLocation?.index}><ArrowUp/> Move earlier</button><button type="button" onClick={()=>move(1)} disabled={!selectedLocation||selectedLocation.index>=selectedLocation.count-1}><ArrowDown/> Move later</button><button type="button" onClick={()=>update(item=>({...item,is_visible:!item.is_visible}))}>{selectedItem.is_visible?<><EyeOff/> Hide</>:<><Eye/> Show</>}</button>{!selectedLocation?.parentKey&&<button type="button" onClick={addChild} disabled={selectedItem.children.length>=6}><Plus/> Add submenu item</button>}<button type="button" className="danger" onClick={remove}><Trash2/> Delete</button></div></>}
   <div className="cms-navigation-save"><button type="button" className="btn btn-outline-primary" disabled={state==='saving'} onClick={save}><Save/> Save navigation draft</button><button type="button" className="btn btn-primary" disabled={state==='saving'} onClick={publish}><Send/> Publish navigation</button></div>{message&&<p className="cms-navigation-message" role="status">{message}</p>}{error&&<p className="cms-navigation-error" role="alert">{error}</p>}<small>{state==='unsaved'?'Unsaved navigation changes':state==='saving'?'Saving…':state==='saved'?'Navigation saved':'Navigation draft'}</small>
  </aside>}
 </>;
}

function NavigationEntry({item,editing,selected,onSelect}:{item:NavigationItem;editing:boolean;selected:string|null;onSelect:(key:string)=>void}){const location=useLocation(),[open,setOpen]=useState(false),button=useRef<HTMLButtonElement>(null),submenuId=`submenu-${useId().replaceAll(':','')}`,children=(editing?item.children:item.children.filter(child=>child.is_visible));useEffect(()=>setOpen(false),[location.pathname]);const choose=(key:string)=>(event:React.SyntheticEvent)=>{if(!editing)return;event.preventDefault();event.stopPropagation();onSelect(key)};const link=(entry:NavigationItem,className:string)=>entry.type==='internal'&&entry.target!=='_blank'?<NavLink className={className} to={entry.path||'/'} aria-label={editing?`Edit navigation item: ${entry.label}`:undefined} onClick={choose(entry.key)}>{entry.label}</NavLink>:<a className={className} href={entry.path||undefined} target={entry.target} rel={entry.target==='_blank'?'noopener noreferrer':undefined} aria-label={editing?`Edit navigation item: ${entry.label}`:undefined} onClick={choose(entry.key)}>{entry.label}</a>;if(!children.length)return link(item,item.path==='/book'?'btn btn-primary ms-lg-3':'nav-link');return <div className={`cms-nav-parent ${open?'open':''} ${selected===item.key?'selected':''}`} onKeyDown={event=>{if(event.key==='Escape'&&open){event.preventDefault();setOpen(false);button.current?.focus()}}}>{link(item,'nav-link')}<button ref={button} type="button" aria-label={`Toggle ${item.label} submenu`} aria-controls={submenuId} aria-expanded={open} onClick={()=>setOpen(value=>!value)}>⌄</button><div id={submenuId} className="cms-submenu" hidden={!open}>{children.map(child=><div className={`${editing?'cms-nav-child-edit':''} ${child.is_visible?'':'cms-nav-item-hidden'} ${selected===child.key?'selected':''}`} key={child.key}>{link(child,'')}</div>)}</div></div>}

function locate(items:NavigationItem[],key:string|null){if(!key||key==='navigation')return null;for(let index=0;index<items.length;index++){const item=items[index];if(item.key===key)return{item,index,count:items.length,parentKey:null as string|null};const childIndex=item.children.findIndex(child=>child.key===key);if(childIndex>=0)return{item:item.children[childIndex],index:childIndex,count:item.children.length,parentKey:item.key}}return null}
