import { PropsWithChildren,ReactNode } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,TextInputProps,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors,spacing } from '@/theme';

export function Screen({children,refreshControl}:{children:ReactNode;refreshControl?:ReactNode}){return <SafeAreaView style={s.safe} edges={['bottom']}><ScrollView contentContainerStyle={s.screen} refreshControl={refreshControl as never}>{children}</ScrollView></SafeAreaView>;}
export function Heading({eyebrow,title,body}:{eyebrow?:string;title:string;body?:string}){return <View style={s.heading}>{eyebrow?<Text style={s.eyebrow}>{eyebrow}</Text>:null}<Text accessibilityRole="header" style={s.title}>{title}</Text>{body?<Text style={s.body}>{body}</Text>:null}</View>;}
export function Card({children,label}:{children:ReactNode;label?:string}){return <View accessible={!!label} accessibilityLabel={label} style={s.card}>{children}</View>;}
export function Button({title,onPress,variant='primary',disabled=false}:{title:string;onPress():void;variant?:'primary'|'secondary'|'danger';disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,s[variant],(pressed||disabled)&&s.faded]}><Text style={[s.buttonText,variant!=='primary'&&s.buttonTextDark]}>{title}</Text></Pressable>;}
export function Field(props:TextInputProps&{label:string;error?:string}){return <View style={s.field}><Text style={s.label}>{props.label}</Text><TextInput {...props} accessibilityLabel={props.label} placeholderTextColor={colors.muted} style={s.input}/>{props.error?<Text accessibilityRole="alert" style={s.error}>{props.error}</Text>:null}</View>;}
export function Loading({label='Loading'}:{label?:string}){return <View accessibilityLabel={label} accessibilityRole="progressbar" style={s.center}><ActivityIndicator color={colors.green}/><Text style={s.body}>{label}…</Text></View>;}
export function Notice({title,body,tone='info'}:{title:string;body:string;tone?:'info'|'error'}){return <View accessibilityRole={tone==='error'?'alert':undefined} style={[s.notice,tone==='error'&&s.noticeError]}><Text style={s.cardTitle}>{title}</Text><Text style={s.body}>{body}</Text></View>;}
export function Empty({title,body}:{title:string;body:string}){return <Card><Text style={s.cardTitle}>{title}</Text><Text style={s.body}>{body}</Text></Card>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},screen:{padding:spacing.md,gap:spacing.md,paddingBottom:spacing.xl},heading:{gap:spacing.xs,marginVertical:spacing.sm},eyebrow:{color:colors.green,fontWeight:'800',letterSpacing:1,textTransform:'uppercase',fontSize:12},title:{fontSize:30,lineHeight:36,fontWeight:'800',color:colors.ink},body:{fontSize:16,lineHeight:24,color:colors.muted},muted:{fontSize:14,lineHeight:20,color:colors.muted},card:{backgroundColor:colors.white,borderColor:colors.line,borderWidth:1,borderRadius:18,padding:spacing.md,gap:spacing.sm},cardTitle:{fontSize:18,lineHeight:24,fontWeight:'700',color:colors.ink},button:{minHeight:48,borderRadius:14,paddingHorizontal:spacing.md,alignItems:'center',justifyContent:'center',backgroundColor:colors.green},primary:{backgroundColor:colors.green},secondary:{backgroundColor:colors.mint},danger:{backgroundColor:colors.dangerSoft},buttonText:{fontSize:16,fontWeight:'800',color:colors.white},buttonTextDark:{color:colors.ink},faded:{opacity:.55},field:{gap:spacing.xs},label:{fontSize:15,fontWeight:'700',color:colors.ink},input:{minHeight:50,borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:spacing.md,fontSize:16,color:colors.ink,backgroundColor:colors.white},error:{color:colors.danger,fontSize:14},center:{minHeight:180,alignItems:'center',justifyContent:'center',gap:spacing.sm},notice:{padding:spacing.md,borderRadius:16,backgroundColor:colors.info,gap:spacing.xs},noticeError:{backgroundColor:colors.dangerSoft},link:{fontSize:16,color:colors.green,fontWeight:'700'},badge:{alignSelf:'flex-start',backgroundColor:colors.mint,color:colors.greenDark,paddingHorizontal:10,paddingVertical:5,borderRadius:99,fontWeight:'700',textTransform:'capitalize'}});
export const text={title:s.cardTitle,body:s.body,muted:s.muted,link:s.link,badge:s.badge};
