<?php
namespace Tests\Feature;
use App\Enums\UserRole;use App\Models\Publication;use App\Models\ResearchClaim;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Laravel\Sanctum\Sanctum;use Tests\TestCase;
class AcademicContentTest extends TestCase{use RefreshDatabase;
 public function test_unverified_records_never_appear_publicly():void{Publication::create(['title'=>'Pending study','category'=>'Breast Cancer','verification_status'=>'pending_review']);$this->getJson('/api/academic/publications')->assertOk()->assertJsonPath('total',0);}
 public function test_only_power_admin_can_review_and_publish_mapped_claim():void{$claim=$this->claim();Sanctum::actingAs(User::factory()->create(['role'=>UserRole::Admin]));$this->getJson('/api/cms/verification-queue')->assertForbidden();$power=User::factory()->create(['role'=>UserRole::PowerAdmin]);Sanctum::actingAs($power);$this->patchJson("/api/cms/verification-queue/{$claim->id}",['decision'=>'verified'])->assertOk();$this->postJson("/api/cms/verification-queue/{$claim->id}/publish")->assertOk();$this->assertDatabaseHas('publications',['doi'=>'10.1000/safe','verification_status'=>'verified']);$this->assertDatabaseHas('audit_logs',['action'=>'research_claim.published','subject_id'=>$claim->id]);$this->getJson('/api/academic/publications?q=Verified')->assertJsonPath('total',1);}
 public function test_rejected_or_unmapped_claim_cannot_be_published():void{$claim=$this->claim();$power=User::factory()->create(['role'=>UserRole::PowerAdmin]);Sanctum::actingAs($power);$this->postJson("/api/cms/verification-queue/{$claim->id}/publish")->assertStatus(422);$this->patchJson("/api/cms/verification-queue/{$claim->id}",['decision'=>'rejected']);$this->postJson("/api/cms/verification-queue/{$claim->id}/publish")->assertStatus(422);}
 public function test_education_requires_review_metadata_and_plain_text_before_publication():void{$power=User::factory()->create(['role'=>UserRole::PowerAdmin]);Sanctum::actingAs($power);$payload=['title'=>'Understanding breast clinic visits','slug'=>'understanding-breast-clinic-visits','summary'=>'A clear guide to preparing for a specialist breast clinic visit.','content'=>'This educational guide explains what patients may expect during an appointment.','author'=>'Practice Education Team','medical_reviewer'=>'Dr. Reviewer','reviewed_at'=>now()->toDateString(),'content_updated_at'=>now()->toDateString(),'category'=>'Breast awareness','tags'=>['appointments'],'medical_disclaimer'=>'This general educational information does not replace personal medical advice or emergency care.'];$article=$this->postJson('/api/cms/education',$payload)->assertCreated()->json('data.id');$this->getJson('/api/education/articles')->assertJsonPath('total',0);$this->postJson("/api/cms/education/{$article}/publish")->assertOk();$this->getJson('/api/education/articles/understanding-breast-clinic-visits')->assertOk()->assertJsonPath('data.medical_reviewer','Dr. Reviewer');$payload['content']='<script>unsafe</script>';$this->postJson('/api/cms/education',$payload+['slug'=>'unsafe'])->assertStatus(422);}
 public function test_publication_search_filter_sort_and_detail_hide_pending_items():void{Publication::create(['title'=>'Verified survivor study','authors'=>'F. Wuraola','category'=>'Survivorship','verification_status'=>'verified','published_at'=>'2023-01-01']);$pending=Publication::create(['title'=>'Pending private study','category'=>'Survivorship','verification_status'=>'pending_review']);$this->getJson('/api/academic/publications?q=survivor&category=Survivorship&sort=title')->assertJsonPath('total',1);$this->getJson('/api/academic/publications/'.$pending->id)->assertNotFound();}
 private function claim():ResearchClaim{return ResearchClaim::create(['category'=>'Publication','claim'=>'Verified publication record','source_title'=>'Journal record','source_url'=>'https://example.test/source','confidence'=>'high','status'=>'pending_review','target_type'=>'publication','target_payload'=>['title'=>'Verified publication','authors'=>'F. Wuraola','journal'=>'Journal','published_at'=>'2025-01-01','doi'=>'10.1000/safe','category'=>'Breast Cancer','external_url'=>'https://example.test/paper','publication_type'=>'journal_article']]);}
}
