<?php
namespace Tests\Feature;
use App\Enums\UserRole;use App\Models\Appointment;use App\Models\Service;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Str;use Tests\TestCase;
class MobileApiTest extends TestCase{use RefreshDatabase;
 public function test_capabilities_are_public_stable_and_truthful():void{$this->getJson('/api/v1/capabilities')->assertOk()->assertJsonPath('data.api_version','v1')->assertJsonPath('data.practice_timezone','Africa/Lagos')->assertJsonPath('data.features.push_notifications',false)->assertJsonPath('data.features.live_video',false);}
 public function test_only_verified_active_claimed_patients_receive_scoped_expiring_token():void{$patient=User::factory()->create(['email'=>'mobile@example.test']);$response=$this->postJson('/api/v1/auth/token',['email'=>$patient->email,'password'=>'password','device_name'=>'Android test'])->assertOk()->assertJsonStructure(['data'=>['access_token','expires_at','user']]);$token=$patient->tokens()->first();$this->assertTrue($token->can('mobile:v1'));$this->assertNotNull($token->expires_at);$staff=User::factory()->create(['role'=>UserRole::Admin]);$this->postJson('/api/v1/auth/token',['email'=>$staff->email,'password'=>'password','device_name'=>'iPhone test'])->assertUnprocessable()->assertJsonPath('error.code','validation_failed');$unverified=User::factory()->unverified()->create();$this->postJson('/api/v1/auth/token',['email'=>$unverified->email,'password'=>'password','device_name'=>'Phone'])->assertUnprocessable();}
 public function test_patient_resources_use_stable_envelopes_and_are_isolated():void{$patient=User::factory()->create();$other=User::factory()->create();$mine=$this->appointment($patient);$this->appointment($other);$token=$patient->createToken('Phone',['mobile:v1'],now()->addDay())->plainTextToken;$this->withToken($token)->getJson('/api/v1/appointments?per_page=1')->assertOk()->assertJsonPath('meta.total',1)->assertJsonPath('data.0.id',$mine->id)->assertJsonStructure(['data','meta'=>['current_page','per_page','total','last_page'],'links'=>['next','previous']]);}
 public function test_cancellation_mutation_replays_without_duplicate_side_effect():void{$patient=User::factory()->create();$appointment=$this->appointment($patient);$token=$patient->createToken('Phone',['mobile:v1'],now()->addDay())->plainTextToken;$id=(string)Str::uuid();$payload=['client_request_id'=>$id,'reason'=>'Cannot attend'];$this->withToken($token)->postJson("/api/v1/appointments/{$appointment->id}/cancellation-requests",$payload)->assertCreated()->assertHeader('X-Idempotent-Replay','false');$this->withToken($token)->postJson("/api/v1/appointments/{$appointment->id}/cancellation-requests",$payload)->assertCreated()->assertHeader('X-Idempotent-Replay','true');$this->assertDatabaseCount('appointment_cancellation_requests',1);$this->assertDatabaseCount('mobile_mutations',1);}
 public function test_v1_errors_and_unavailable_push_registration_are_stable():void{$this->getJson('/api/v1/me')->assertUnauthorized()->assertJsonPath('error.code','unauthenticated');$patient=User::factory()->create();$token=$patient->createToken('Phone',['mobile:v1'],now()->addDay())->plainTextToken;$this->withToken($token)->postJson('/api/v1/devices/push-token',['token'=>'never-stored'])->assertStatus(409)->assertJsonPath('error.code','conflict');}
 private function appointment(User $patient):Appointment{$service=Service::firstOrCreate(['slug'=>'mobile-review'],['name'=>'Mobile review','summary'=>'Review']);$start=now()->addWeek();return Appointment::create(['public_id'=>Str::uuid(),'patient_id'=>$patient->id,'service_id'=>$service->id,'starts_at'=>$start,'ends_at'=>$start->copy()->addMinutes(45),'status'=>'confirmed','consultation_method'=>'in_person','reason'=>'Review']);}
}
