<?php
namespace Tests\Feature;
use App\Enums\UserRole;use App\Models\AuditLog;use App\Models\CmsPreviewToken;use App\Models\CmsPage;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Artisan;use Laravel\Sanctum\Sanctum;use Tests\TestCase;
class SecurityHardeningTest extends TestCase{use RefreshDatabase;
 public function test_security_headers_are_applied_to_web_and_api_responses():void{$this->get('/')->assertHeader('X-Content-Type-Options','nosniff')->assertHeader('X-Frame-Options','DENY')->assertHeader('Content-Security-Policy');$this->getJson('/api/public')->assertHeader('Referrer-Policy','strict-origin-when-cross-origin');}
 public function test_suspicious_upload_is_rejected_before_private_storage():void{$patient=User::factory()->create();Sanctum::actingAs($patient);$file=UploadedFile::fake()->createWithContent('referral.pdf',"%PDF-1.4\n<?php echo 'unsafe';");$this->post('/api/me/documents',['label'=>'Referral','document'=>$file],['Accept'=>'application/json'])->assertUnprocessable();$this->assertDatabaseCount('patient_documents',0);$this->assertDatabaseHas('audit_logs',['actor_id'=>$patient->id,'action'=>'document.upload_rejected']);}
 public function test_devices_are_isolated_and_owner_can_revoke_one():void{$owner=User::factory()->create();$other=User::factory()->create();$one=$owner->createToken('Owner phone',['profile:read'],now()->addDay())->accessToken;$otherToken=$other->createToken('Other phone',['profile:read'],now()->addDay())->accessToken;Sanctum::actingAs($owner);$this->getJson('/api/me/devices')->assertOk()->assertJsonCount(1,'data')->assertJsonPath('data.0.name','Owner phone');$this->deleteJson('/api/me/devices/'.$otherToken->id)->assertNotFound();$this->deleteJson('/api/me/devices/'.$one->id)->assertOk();$this->assertDatabaseHas('audit_logs',['action'=>'identity.mobile_token_revoked','actor_id'=>$owner->id]);}
 public function test_audit_log_access_is_power_admin_only_and_filters_sensitive_metadata():void{$patient=User::factory()->create();AuditLog::create(['actor_id'=>$patient->id,'action'=>'identity.test','metadata'=>['device'=>'phone','token'=>'must-not-leak','nested'=>['password'=>'no']]]);Sanctum::actingAs(User::factory()->create(['role'=>UserRole::Admin]));$this->getJson('/api/cms/audit-logs')->assertForbidden();Sanctum::actingAs(User::factory()->create(['role'=>UserRole::PowerAdmin]));$this->getJson('/api/cms/audit-logs?action=identity')->assertOk()->assertJsonPath('data.0.metadata.device','phone')->assertJsonMissingPath('data.0.metadata.token')->assertJsonMissingPath('data.0.metadata.nested.password');}
 public function test_readiness_is_generic_and_retention_defaults_to_dry_run():void{$this->getJson('/api/ready')->assertOk()->assertJsonStructure(['status','checks'=>['database','private_storage']])->assertJsonMissingPath('database.host');$user=User::factory()->create();$page=CmsPage::create(['title'=>'Preview','slug'=>'preview-test','template'=>'standard','created_by'=>$user->id]);CmsPreviewToken::create(['cms_page_id'=>$page->id,'token_hash'=>hash('sha256','old'),'expires_at'=>now()->subDay(),'created_by'=>$user->id]);Artisan::call('practice:prune-expired');$this->assertDatabaseCount('cms_preview_tokens',1);Artisan::call('practice:prune-expired',['--execute'=>true]);$this->assertDatabaseCount('cms_preview_tokens',0);}
}
