<?php
namespace App\Http\Controllers\Cms;
use App\Http\Controllers\Controller;use App\Models\Achievement;use App\Models\AuditLog;use App\Models\CareerEntry;use App\Models\Publication;use App\Models\ResearchClaim;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Validation\ValidationException;
class VerificationQueueController extends Controller{
 public function index(Request $request):JsonResponse{$status=$request->validate(['status'=>['nullable','in:pending_review,verified,rejected,published']])['status']??'pending_review';return response()->json(ResearchClaim::where('status',$status)->latest()->paginate(25));}
 public function decide(Request $request,ResearchClaim $claim):JsonResponse{$decision=$request->validate(['decision'=>['required','in:verified,rejected']])['decision'];$claim->update(['status'=>$decision,'reviewed_by'=>$request->user()->id,'reviewed_at'=>now()]);$this->audit($request,$claim,'research_claim.reviewed',['decision'=>$decision]);return response()->json(['data'=>$claim]);}
 public function publish(Request $request,ResearchClaim $claim):JsonResponse{abort_unless($claim->status==='verified',422,'Only verified claims can be published.');$payload=$claim->target_payload??[];$record=match($claim->target_type){'publication'=>Publication::updateOrCreate(['doi'=>$payload['doi']??null],$payload+['verification_status'=>'verified']),'career'=>CareerEntry::create($payload+['verification_status'=>'verified','is_published'=>true]),'achievement'=>Achievement::create($payload+['verification_status'=>'verified','is_published'=>true]),default=>throw ValidationException::withMessages(['target_type'=>'This claim has no supported publishing destination.'])};$claim->update(['status'=>'published']);$this->audit($request,$claim,'research_claim.published',['target_type'=>$claim->target_type,'record_id'=>$record->id]);return response()->json(['data'=>$claim,'record_id'=>$record->id]);}
 private function audit(Request $request,ResearchClaim $claim,string $action,array $metadata):void{AuditLog::create(['actor_id'=>$request->user()->id,'action'=>$action,'subject_type'=>ResearchClaim::class,'subject_id'=>$claim->id,'metadata'=>$metadata]);}
}
