import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { fireEvent,render,screen,waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach,expect,test,vi } from 'vitest';
import { api } from '../api';
import AccountSecurityPage from './AccountSecurityPage';
import AuditLogPage from './AuditLogPage';
import StaffAccountsPage from './StaffAccountsPage';

vi.mock('../api',()=>({api:{get:vi.fn(),post:vi.fn(),patch:vi.fn(),delete:vi.fn()}}));
const get=vi.mocked(api.get),post=vi.mocked(api.post),patch=vi.mocked(api.patch),remove=vi.mocked(api.delete);
function view(node:React.ReactNode,path:string){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[path]}>{node}</MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{get.mockReset();post.mockReset();patch.mockReset();remove.mockReset();post.mockResolvedValue({data:{}} as any);patch.mockResolvedValue({data:{}} as any);remove.mockResolvedValue({data:{}} as any)});

test('Power Admin can filter, invite and open a protected account edit',async()=>{get.mockImplementation(async(url:string)=>url==='/staff/dashboard'?{data:{role:'power_admin'}} as any:{data:{data:[{id:4,name:'Ada Admin',email:'ada@example.test',phone:'0801',role:'admin',is_active:true,email_verified_at:'2026-01-01',account_claimed_at:'2026-01-01'}],current_page:1,last_page:1}} as any);view(<StaffAccountsPage/>,'/staff/accounts');expect(await screen.findByRole('heading',{name:'Accounts'})).toBeInTheDocument();expect(await screen.findByLabelText('Filter by role')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Full name'),{target:{value:'New Moderator'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'new@example.test'}});fireEvent.change(screen.getByLabelText('Invite role'),{target:{value:'moderator'}});fireEvent.change(screen.getByLabelText('Confirm with your password'),{target:{value:'password'}});fireEvent.click(screen.getByRole('button',{name:'Create invitation'}));await waitFor(()=>expect(post).toHaveBeenCalledWith('/staff/accounts',expect.objectContaining({role:'moderator',current_password:'password'})));fireEvent.click(await screen.findByRole('button',{name:'Edit'}));expect(screen.getByRole('dialog')).toHaveAccessibleName('Edit Ada Admin');fireEvent.click(screen.getByLabelText('Account is active'));expect(screen.getByLabelText('Confirm with your password')).toBeInTheDocument();});

test('Admin sees patient-only invitation controls',async()=>{get.mockImplementation(async(url:string)=>url==='/staff/dashboard'?{data:{role:'admin'}} as any:{data:{data:[],current_page:1,last_page:1}} as any);view(<StaffAccountsPage/>,'/staff/accounts');await screen.findByRole('heading',{name:'Accounts'});expect(screen.queryByLabelText('Invite role')).not.toBeInTheDocument();expect(screen.queryByLabelText('Confirm with your password')).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('Full name'),{target:{value:'Patient One'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'patient@example.test'}});fireEvent.click(screen.getByRole('button',{name:'Create invitation'}));await waitFor(()=>expect(post).toHaveBeenCalledWith('/staff/accounts',expect.objectContaining({role:'patient'})));});

test('Account security lists and revokes only non-current access',async()=>{get.mockImplementation(async(url:string)=>{if(url==='/me')return{data:{user:{role:'patient'}}} as any;if(url==='/me/devices')return{data:{data:[{id:2,name:'Patient phone',last_used_at:null,expires_at:'2026-12-01'}]}} as any;return{data:{data:[{reference:'current',current:true,device:'Chrome',ip_address:'203.0.113.x',last_active_at:'2026-08-30T08:00:00Z'},{reference:'other',current:false,device:'Firefox',ip_address:'203.0.113.x',last_active_at:'2026-08-29T08:00:00Z'}]}} as any});view(<AccountSecurityPage/>,'/security');expect(await screen.findByText(/Chrome · This browser/)).toBeInTheDocument();expect(screen.getAllByRole('button',{name:'Revoke'})).toHaveLength(2);fireEvent.click(screen.getAllByRole('button',{name:'Revoke'})[0]);await waitFor(()=>expect(remove).toHaveBeenCalledWith('/me/sessions/other'));});

test('Audit log exposes bounded filters, safe changed fields and pagination',async()=>{get.mockResolvedValue({data:{data:[{id:1,action:'identity.account_updated',actor:{name:'Power Admin'},subject_type:'User',subject_id:8,metadata:{fields:['role','is_active']},created_at:'2026-08-30T08:00:00Z'}],current_page:1,last_page:1}} as any);view(<AuditLogPage/>,'/staff/audit');expect(await screen.findByText('Changed: role, is_active')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Action starts with'),{target:{value:'identity.'}});fireEvent.change(screen.getByLabelText('Actor ID'),{target:{value:'3'}});await waitFor(()=>expect(get).toHaveBeenLastCalledWith('/cms/audit-logs',{params:expect.objectContaining({action:'identity.',actor_id:'3',page:1})}));expect(screen.getByRole('button',{name:'Next'})).toBeDisabled();});
