import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { fireEvent,render,screen,waitFor } from '@testing-library/react';
import { MemoryRouter,Route,Routes } from 'react-router-dom';
import { beforeEach,expect,test,vi } from 'vitest';
import { Layout } from '../App';import StaffDashboardPage from './StaffDashboardPage';import CmsEditorPage from './CmsEditorPage';import CmsPublicPage from './CmsPublicPage';import { api } from '../api';
vi.mock('../api',()=>({api:{get:vi.fn(),post:vi.fn(),put:vi.fn(),patch:vi.fn(),delete:vi.fn()}}));
const get=vi.mocked(api.get),put=vi.mocked(api.put),post=vi.mocked(api.post);
function view(node:React.ReactNode,path='/staff'){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[path]}>{node}</MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{get.mockReset();put.mockReset();post.mockReset();put.mockResolvedValue({data:{}} as any);post.mockResolvedValue({data:{}} as any)});
test('Power Admin dashboard exposes working operational and publishing links',async()=>{get.mockImplementation(async(url:string)=>url==='/staff/dashboard'?{data:{role:'power_admin',metrics:{today:0,pending:0,online_today:0,unclaimed_patients:0},pending_requests:[],today_appointments:[]}} as any:{data:{data:[]}} as any);view(<StaffDashboardPage/>);expect(await screen.findByRole('link',{name:/Website pages/})).toHaveAttribute('href','/staff/cms');expect(screen.getByRole('link',{name:/Publications/})).toHaveAttribute('href','/staff/research-review');expect(screen.getByRole('link',{name:/Education/})).toHaveAttribute('href','/staff/education');expect(screen.getByRole('link',{name:/Audit log/})).toHaveAttribute('href','/staff/audit');expect(screen.getByRole('link',{name:/Appointments/})).toHaveAttribute('href','/staff/calendar');expect(screen.getByRole('link',{name:/Accounts/})).toHaveAttribute('href','/staff/accounts');expect(screen.getByRole('link',{name:/Security/})).toHaveAttribute('href','/security');});
test('ordinary staff do not receive Power Admin publishing links',async()=>{get.mockResolvedValue({data:{role:'admin',metrics:{today:0,pending:0,online_today:0,unclaimed_patients:0},pending_requests:[],today_appointments:[]}} as any);view(<StaffDashboardPage/>);await screen.findByRole('heading',{name:'Practice today'});expect(screen.queryByRole('link',{name:/Website pages/})).not.toBeInTheDocument();expect(screen.getByRole('link',{name:/Inbox/})).toHaveAttribute('href','/staff/inbox');expect(screen.getByRole('link',{name:/Accounts/})).toHaveAttribute('href','/staff/accounts');});
test('public site provides an authenticated Power Admin edit toggle and persistent toolbar',async()=>{get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:{data:{data:{}}} as any);view(<Layout><h1>Public page</h1></Layout>,'/research');const toggle=await screen.findByRole('button',{name:'Edit site'});fireEvent.click(toggle);expect(screen.getByRole('toolbar',{name:'Website editor'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Select'})).toBeDisabled();expect(screen.getByRole('button',{name:'Add Section'})).toBeDisabled();expect(screen.getByRole('button',{name:'Undo'})).toBeDisabled();expect(screen.getByRole('button',{name:'Redo'})).toBeDisabled();expect(screen.getByRole('button',{name:'Preview'})).toBeDisabled();expect(screen.getByRole('button',{name:'Save Draft'})).toBeDisabled();expect(screen.getByRole('button',{name:'Publish'})).toBeDisabled();expect(screen.getByRole('button',{name:'Exit Edit Mode'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Page settings'})).toHaveAttribute('href','/staff/cms?slug=research');});
test('published navigation and theme settings drive the public layout',async()=>{get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:null}} as any:{data:{data:{navigation:[{label:'Care options',path:'/services'},{label:'Start here',path:'/book'},{label:'Research partner',type:'external',path:'https://example.org/research',target:'_blank'},{label:'Hidden',path:'/contact',is_visible:false}],theme:{palette:'plum',density:'compact',heading_style:'modern'}}}} as any);const rendered=view(<Layout><h1>Public page</h1></Layout>);expect(await screen.findByRole('link',{name:'Care options'})).toHaveAttribute('href','/services');expect(screen.getByRole('link',{name:'Start here'})).toHaveAttribute('href','/book');expect(screen.getByRole('link',{name:'Research partner'})).toHaveAttribute('href','https://example.org/research');expect(screen.getByRole('link',{name:'Research partner'})).toHaveAttribute('target','_blank');expect(screen.queryByRole('link',{name:'Hidden'})).not.toBeInTheDocument();expect(screen.queryByRole('link',{name:'About'})).not.toBeInTheDocument();expect(rendered.container.querySelector('.site-shell')).toHaveClass('theme-plum','density-compact','headings-modern');});
test('collapsed navigation exposes accurate accessible state',async()=>{get.mockResolvedValue({data:{}} as any);view(<Layout><h1>Public page</h1></Layout>);const toggle=screen.getByRole('button',{name:'Open navigation'});expect(toggle).toHaveAttribute('aria-expanded','false');fireEvent.click(toggle);expect(screen.getByRole('button',{name:'Close navigation'})).toHaveAttribute('aria-expanded','true');expect(document.getElementById('main-navigation-links')).toHaveClass('show');});
test('public navigation supports skip, Escape, submenu state and route focus',async()=>{get.mockResolvedValue({data:{}} as any);view(<Layout><h1>Public page</h1></Layout>,'/');const skip=screen.getByRole('link',{name:'Skip to main content'});expect(skip).toHaveAttribute('href','#main-content');const menu=screen.getByRole('button',{name:'Open navigation'});fireEvent.click(menu);fireEvent.keyDown(document,{key:'Escape'});expect(menu).toHaveFocus();expect(menu).toHaveAttribute('aria-expanded','false');const submenu=screen.getByRole('button',{name:'Toggle Research submenu'});fireEvent.click(submenu);expect(submenu).toHaveAttribute('aria-expanded','true');expect(submenu).toHaveAttribute('aria-controls');fireEvent.keyDown(submenu,{key:'Escape'});expect(submenu).toHaveFocus();expect(submenu).toHaveAttribute('aria-expanded','false');fireEvent.click(screen.getByRole('link',{name:'About'}));await waitFor(()=>expect(document.getElementById('main-content')).toHaveFocus());});
test('rendered header navigation is edited as a private draft and explicitly published',async()=>{
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(true);
 const careKey='00000000-0000-4000-8000-000000000101',aboutKey='00000000-0000-4000-8000-000000000102',draft=[{key:careKey,label:'Care',type:'internal',path:'/services',target:'_self',is_visible:true,children:[]},{key:aboutKey,label:'About',type:'internal',path:'/about',target:'_self',is_visible:true,children:[]}];
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{navigation:[{key:'00000000-0000-4000-8000-000000000100',label:'Published home',type:'internal',path:'/',target:'_self',is_visible:true,children:[]}]}}} as any:url==='/cms/settings'?{data:{data:{navigation:{draft_value:draft}}}} as any:{data:{data:{}}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{draft_value:payload.value}}}) as any);
 const rendered=view(<Layout><h1>Public page</h1></Layout>,'/');
 expect(await screen.findByRole('link',{name:'Published home'})).toHaveAttribute('href','/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 fireEvent.click(await screen.findByRole('link',{name:'Edit navigation item: Care'}));
 fireEvent.change(screen.getByLabelText('Navigation label'),{target:{value:'Care options'}});
 expect(screen.getByRole('link',{name:'Edit navigation item: Care options'})).toBeInTheDocument();
 fireEvent.change(screen.getByLabelText('Destination type'),{target:{value:'external'}});
 fireEvent.change(screen.getByLabelText('Navigation destination'),{target:{value:'https://example.org/care'}});
 fireEvent.change(screen.getByLabelText('Open link'),{target:{value:'_blank'}});
 fireEvent.click(screen.getByRole('button',{name:'Hide'}));
 expect(rendered.container.querySelector('.cms-nav-item-hidden')).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Show'}));
 fireEvent.click(screen.getByRole('button',{name:'Add submenu item'}));
 fireEvent.change(screen.getByLabelText('Navigation label'),{target:{value:'Patient guide'}});
 fireEvent.change(screen.getByLabelText('Navigation destination'),{target:{value:'/p/patient-guide'}});
 fireEvent.click(screen.getByRole('link',{name:'Edit navigation item: Care options'}));
 fireEvent.click(screen.getByRole('button',{name:'Move later'}));
 fireEvent.click(screen.getByRole('button',{name:'Save navigation draft'}));
 await waitFor(()=>expect(put).toHaveBeenCalledWith('/cms/settings/navigation',{value:expect.arrayContaining([expect.objectContaining({key:careKey,label:'Care options',type:'external',path:'https://example.org/care',target:'_blank',children:[expect.objectContaining({label:'Patient guide',path:'/p/patient-guide'})]})])}));
 expect(screen.getByText(/Navigation draft saved privately/)).toBeInTheDocument();
 fireEvent.click(screen.getByRole('link',{name:'Edit navigation item: About'}));
 confirm.mockReturnValue(false);fireEvent.click(screen.getByRole('button',{name:'Delete'}));
 expect(screen.getByRole('link',{name:'Edit navigation item: About'})).toBeInTheDocument();
 confirm.mockReturnValue(true);fireEvent.click(screen.getByRole('button',{name:'Delete'}));
 expect(screen.queryByRole('link',{name:'Edit navigation item: About'})).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Edit rendered navigation'}));
 fireEvent.click(screen.getByRole('button',{name:'Publish navigation'}));
 await waitFor(()=>expect(post).toHaveBeenCalledWith('/cms/settings/navigation/publish'));
 expect(screen.getByText(/Navigation published/)).toBeInTheDocument();
 confirm.mockRestore();
});
test('Edit Mode creates a safe template page and opens its actual private URL',async()=>{
 const section={id:10,section_key:'new-hero',type:'hero',sort_order:0,is_visible:true,content:{eyebrow:'New page',heading:'Patient support guide',text:'Editable introduction'},presentation:{}};
 get.mockImplementation(async(url:string)=>{if(url==='/me')return{data:{user:{role:'power_admin'}}} as any;if(url==='/cms/public-settings')return{data:{data:{}}} as any;if(url==='/cms/settings')return{data:{data:{}}} as any;if(url==='/cms/pages')return{data:{data:[{id:7,slug:'patient-support-guide'}]}} as any;if(url==='/cms/pages/7')return{data:{data:{id:7,title:'Patient support guide',slug:'patient-support-guide',lock_version:0,sections:[section]}}} as any;if(url==='/content/pages/patient-support-guide')throw {response:{status:404}};return{data:{data:{}}} as any});
 post.mockRejectedValueOnce({response:{data:{errors:{slug:['That page address is already in use.']}}}}).mockResolvedValueOnce({data:{data:{id:7,slug:'patient-support-guide',public_path:'/p/patient-support-guide'}}} as any);
 view(<Layout><Routes><Route path="/about" element={<h1>About</h1>}/><Route path="/p/:slug" element={<CmsPublicPage/>}/></Routes></Layout>,'/about');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 fireEvent.click(screen.getByRole('button',{name:'New Page'}));
 fireEvent.change(screen.getByLabelText('Page name'),{target:{value:'Patient support guide'}});
 expect(screen.getByRole('textbox',{name:/Page address/})).toHaveValue('patient-support-guide');
 fireEvent.click(screen.getByRole('radio',{name:/Starter template/}));
 fireEvent.change(screen.getByLabelText('Starter template'),{target:{value:'landing'}});
 fireEvent.click(screen.getByRole('button',{name:'Create and open page'}));
 expect(await screen.findByRole('alert')).toHaveTextContent('already in use');
 expect(screen.getByLabelText('Page name')).toHaveValue('Patient support guide');
 fireEvent.change(screen.getByRole('textbox',{name:/Page address/}),{target:{value:'patient-support-guide'}});
 fireEvent.click(screen.getByRole('button',{name:'Create and open page'}));
 await waitFor(()=>expect(post).toHaveBeenLastCalledWith('/cms/pages',{title:'Patient support guide',slug:'patient-support-guide',start_mode:'template',template:'landing'}));
 expect(await screen.findByText('Editable introduction')).toBeInTheDocument();
 expect(screen.getByText(/Edit Mode is on/)).toBeInTheDocument();
 await waitFor(()=>expect(screen.getByRole('button',{name:'Preview'})).toBeEnabled());
});
test('website editor offers an explicit existing-page dropdown',async()=>{get.mockImplementation(async(url:string)=>url==='/cms/pages'?{data:{data:[{id:1,title:'About the practice',slug:'about-practice',status:'draft'},{id:2,title:'Patient guide',slug:'patient-guide',status:'published'}]}} as any:{data:{data:{id:1,title:'About the practice',slug:'about-practice',sections:[]}}} as any);view(<CmsEditorPage/>,'/staff/cms');const picker=await screen.findByRole('combobox',{name:'Choose an existing page'});await waitFor(()=>expect(picker).toHaveValue('1'));expect(screen.getByRole('option',{name:'Patient guide — /patient-guide (published)'})).toBeInTheDocument();fireEvent.change(picker,{target:{value:'2'}});expect(picker).toHaveValue('2');});
test('website editor exposes structured content presentation visibility and version controls',async()=>{get.mockImplementation(async(url:string)=>{if(url==='/cms/pages')return{data:{data:[{id:1,title:'Home',slug:'home',status:'published'}]}} as any;if(url==='/cms/pages/1')return{data:{data:{id:1,title:'Home',slug:'home',template:'landing',status:'published',sections:[{id:10,section_key:'hero-one',type:'hero',is_visible:true,content:{eyebrow:'Care',heading:'Whole-person care',text:'Introduction',primary_label:'Book',primary_url:'/book'},presentation:{background:'ivory',alignment:'left',width:'normal',spacing:'normal'}}]}}} as any;if(url==='/cms/pages/1/versions')return{data:{data:[{id:4,version:2,reason:'Section updated',created_at:'2026-08-28T10:00:00Z'}]}} as any;return{data:{data:{}}} as any});view(<CmsEditorPage/>,'/staff/cms?slug=home');expect(await screen.findByDisplayValue('Whole-person care')).toBeInTheDocument();expect(screen.getByLabelText('Primary button label')).toHaveValue('Book');expect(screen.getByLabelText('Background')).toHaveValue('ivory');expect(screen.getByLabelText(/Show this section/)).toBeChecked();fireEvent.click(screen.getByText('Version history'));expect(screen.getByRole('button',{name:/Restore as draft/})).toBeInTheDocument();});
test('website settings distinguish private draft from explicit publish',async()=>{get.mockImplementation(async(url:string)=>url==='/cms/pages'?{data:{data:[]}} as any:url==='/cms/settings'?{data:{data:{navigation:{draft_value:[{label:'Home',path:'/'}]},theme:{draft_value:{palette:'wine',density:'comfortable',heading_style:'editorial'}}}}} as any:{data:{data:[]}} as any);view(<CmsEditorPage/>,'/staff/cms');fireEvent.click(await screen.findByRole('button',{name:/Navigation & theme/}));expect(screen.getByRole('heading',{name:'Navigation & theme'})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Colour palette'),{target:{value:'plum'}});fireEvent.click(screen.getByRole('button',{name:/Save private draft/}));await waitFor(()=>expect(put).toHaveBeenCalledTimes(2));expect(post).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:/Save & publish/}));await waitFor(()=>expect(post).toHaveBeenCalledWith('/cms/settings/navigation/publish'));expect(post).toHaveBeenCalledWith('/cms/settings/theme/publish');});
test('persistent public Edit Mode uses a caret in the rendered element and atomically saves live typography',async()=>{const published={title:'Home',sections:[{id:10,section_key:'one',type:'text',is_visible:true,content:{heading:'Published heading',body:'Published paragraph'},presentation:{}}]},draft={id:1,title:'Home',slug:'home',lock_version:3,sections:[{id:10,section_key:'one',type:'text',sort_order:0,is_visible:true,content:{heading:'Draft heading',body:'Draft paragraph'},presentation:{}}]};get.mockImplementation(async(url:string)=>{if(url==='/me')return{data:{user:{role:'power_admin'}}} as any;if(url==='/cms/public-settings')return{data:{data:{}}} as any;if(url==='/content/pages/home')return{data:{data:published}} as any;if(url==='/cms/pages')return{data:{data:[{id:1,slug:'home'}]}} as any;if(url==='/cms/pages/1')return{data:{data:draft}} as any;return{data:{data:[]}} as any});put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:4,sections:payload.sections}}}) as any);view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));expect(await screen.findByText(/Edit Mode is on/)).toBeInTheDocument();const paragraph=await screen.findByText('Draft paragraph');fireEvent.doubleClick(paragraph);expect(screen.getByRole('textbox',{name:'Editing Body text'})).toBe(paragraph);expect(paragraph).toHaveFocus();paragraph.textContent='Updated in place';fireEvent.input(paragraph);fireEvent.change(screen.getByLabelText('Font family'),{target:{value:'modern'}});fireEvent.click(screen.getByRole('button',{name:/Bold/}));expect(paragraph).toHaveStyle({fontFamily:'var(--sans)',fontWeight:'700'});expect(screen.getByText('Unsaved changes')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Undo'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Done'}));fireEvent.click(screen.getByRole('button',{name:'Save Draft'}));await waitFor(()=>expect(put).toHaveBeenCalledWith('/cms/pages/1/visual-draft',expect.objectContaining({lock_version:3,sections:[expect.objectContaining({content:expect.objectContaining({body:'Updated in place',body_marks:[]}),presentation:expect.objectContaining({text_styles:expect.objectContaining({body:expect.objectContaining({font_family:'modern',bold:true})})})})]})));expect(await screen.findByText('Draft saved')).toBeInTheDocument();});
test('rendered buttons expose complete live action and appearance controls',async()=>{
 const section={id:10,section_key:'hero',type:'hero',sort_order:0,is_visible:true,content:{heading:'Care',text:'Choose care',primary_label:'Book now',primary_url:'/book',primary_style:'primary',primary_icon:'arrow',primary_visibility:'show'},presentation:{}};
 const draft={id:1,title:'Home',slug:'home',lock_version:5,sections:[section]};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections:[section]}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:{data:{data:[]}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:6,sections:payload.sections}}}) as any);
 view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 const button=await screen.findByRole('button',{name:'Edit Primary button text'});
 const saveButton=screen.getByRole('button',{name:'Save Draft'});
 await waitFor(()=>expect(saveButton).toBeEnabled());
 fireEvent.click(button);
 const text=screen.getByRole('textbox',{name:'Editing Primary button text'});
 text.textContent='Start care';
 fireEvent.input(text);
 await waitFor(()=>expect(screen.getByRole('toolbar',{name:'Website editor'}).textContent).toContain('Unsaved changes'));
 fireEvent.change(screen.getByLabelText('Button action'),{target:{value:'external'}});
 fireEvent.change(screen.getByLabelText('Button destination'),{target:{value:'https://example.org/care'}});
 fireEvent.change(screen.getByLabelText('Open link'),{target:{value:'_blank'}});
 fireEvent.change(screen.getByLabelText('Button icon'),{target:{value:'external'}});
 fireEvent.change(screen.getByLabelText('Icon position'),{target:{value:'left'}});
 fireEvent.change(screen.getByLabelText('Button background'),{target:{value:'black'}});
 fireEvent.change(screen.getByLabelText('Corner radius'),{target:{value:'24'}});
 expect(screen.getByRole('button',{name:'Edit Primary button text'})).toHaveStyle({backgroundColor:'#21191c',borderRadius:'24px'});
 expect(screen.getByText('Unsaved changes')).toBeInTheDocument();
 expect(saveButton).toBeEnabled();
 fireEvent.click(saveButton);
 await waitFor(()=>expect(put).toHaveBeenCalledWith('/cms/pages/1/visual-draft',expect.objectContaining({lock_version:5,sections:[expect.objectContaining({content:expect.objectContaining({primary_label:'Start care',primary_action:'external',primary_url:'https://example.org/care',primary_target:'_blank',primary_icon:'external',primary_icon_position:'left'}),presentation:expect.objectContaining({button_styles:expect.objectContaining({primary:expect.objectContaining({background_color:'black',border_radius:'24'})})})})]})));
});
test('linked text is selected in place, edited safely, and removed without deleting its words',async()=>{
 const section={id:10,section_key:'copy',type:'text',sort_order:0,is_visible:true,content:{heading:'Help',body:'Read our guide today',body_marks:[{type:'link',start:9,end:14,url:'/guide',target:'_self',action:'internal'}]},presentation:{}};
 const draft={id:1,title:'Home',slug:'home',lock_version:8,sections:[section]};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections:[section]}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:{data:{data:[]}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:payload.lock_version+1,sections:payload.sections}}}) as any);
 view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 const saveButton=screen.getByRole('button',{name:'Save Draft'});
 await waitFor(()=>expect(saveButton).toBeEnabled());
 fireEvent.click(await screen.findByRole('link',{name:'Edit link: guide'}));
 expect(screen.getByLabelText('Link display text')).toHaveValue('guide');
 fireEvent.change(screen.getByLabelText('Link display text'),{target:{value:'support guide'}});
 fireEvent.change(screen.getByLabelText('Link action'),{target:{value:'external'}});
 fireEvent.change(screen.getByLabelText('Link destination'),{target:{value:'https://example.org/support'}});
 fireEvent.change(screen.getByLabelText('Open link'),{target:{value:'_blank'}});
 expect(screen.getByRole('textbox',{name:'Editing Body text'})).toHaveTextContent('Read our support guide today');
 fireEvent.click(saveButton);
 await waitFor(()=>expect(put).toHaveBeenCalledWith('/cms/pages/1/visual-draft',expect.objectContaining({lock_version:8,sections:[expect.objectContaining({content:expect.objectContaining({body:'Read our support guide today',body_marks:[expect.objectContaining({type:'link',start:9,end:22,url:'https://example.org/support',target:'_blank',action:'external'})]})})]})));
 fireEvent.click(screen.getByRole('button',{name:'Remove link but keep text'}));
 expect(screen.getByRole('textbox',{name:'Editing Body text'})).toHaveTextContent('Read our support guide today');
 fireEvent.click(saveButton);
 await waitFor(()=>expect(put).toHaveBeenLastCalledWith('/cms/pages/1/visual-draft',expect.objectContaining({lock_version:9,sections:[expect.objectContaining({content:expect.objectContaining({body:'Read our support guide today',body_marks:[]})})]})));
});
test('selected rendered words can become an email link without entering raw protocols',async()=>{
 const section={id:10,section_key:'copy',type:'text',sort_order:0,is_visible:true,content:{heading:'Help',body:'Email our team today',body_marks:[]},presentation:{}};
 const draft={id:1,title:'Home',slug:'home',lock_version:2,sections:[section]};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections:[section]}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:{data:{data:[]}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:3,sections:payload.sections}}}) as any);
 view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 const saveButton=screen.getByRole('button',{name:'Save Draft'});
 await waitFor(()=>expect(saveButton).toBeEnabled());
 const paragraph=await screen.findByText('Email our team today');
 fireEvent.doubleClick(paragraph);
 const textbox=screen.getByRole('textbox',{name:'Editing Body text'}),node=textbox.firstChild as Text,range=document.createRange(),selection=window.getSelection();
 range.setStart(node,10);range.setEnd(node,14);selection?.removeAllRanges();selection?.addRange(range);fireEvent.mouseUp(textbox);
 fireEvent.click(screen.getByRole('button',{name:'Make selected text a link'}));
 fireEvent.change(screen.getByLabelText('Link action'),{target:{value:'email'}});
 fireEvent.change(screen.getByLabelText('Link destination'),{target:{value:'care@example.org'}});
 fireEvent.click(saveButton);
 await waitFor(()=>expect(put).toHaveBeenCalledWith('/cms/pages/1/visual-draft',expect.objectContaining({lock_version:2,sections:[expect.objectContaining({content:expect.objectContaining({body:'Email our team today',body_marks:[expect.objectContaining({type:'link',start:10,end:14,url:'mailto:care@example.org',action:'email',target:'_self'})]})})]})));
});
test('selected sections support responsive styling, lifecycle controls, drag reorder, and atomic save',async()=>{
 const hero={id:10,section_key:'hero-one',type:'hero',sort_order:0,is_visible:true,content:{heading:'First section',text:'First copy'},presentation:{}},copy={id:11,section_key:'copy-two',type:'text',sort_order:1,is_visible:true,content:{heading:'Second section',body:'Second copy'},presentation:{}},draft={id:1,title:'Home',slug:'home',lock_version:12,sections:[hero,copy]};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections:[hero,copy]}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:{data:{data:[]}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:payload.lock_version+1,sections:payload.sections}}}) as any);
 const rendered=view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 const saveButton=screen.getByRole('button',{name:'Save Draft'});
 await waitFor(()=>expect(saveButton).toBeEnabled());
 fireEvent.click(screen.getByRole('button',{name:'Edit hero section properties'}));
 fireEvent.click(screen.getByRole('button',{name:'Mobile'}));
 fireEvent.change(screen.getByLabelText('Background'),{target:{value:'wine'}});
 fireEvent.change(screen.getByLabelText('Layout'),{target:{value:'grid'}});
 fireEvent.change(screen.getByLabelText('Columns'),{target:{value:'2'}});
 expect(rendered.container.querySelector('article')).toHaveClass('cms-editor-viewport-mobile');
 expect(rendered.container.querySelector('.cms-section')).toHaveClass('cms-bg-wine','cms-layout-grid','cms-columns-2');
 fireEvent.click(screen.getByRole('button',{name:'Move down'}));
 expect(Array.from(rendered.container.querySelectorAll('.cms-section h2,.cms-section h1')).map(node=>node.textContent)).toEqual(['Second section','First section']);
 fireEvent.click(screen.getByRole('button',{name:'Duplicate'}));
 fireEvent.click(screen.getByRole('button',{name:'Hide'}));
 expect(rendered.container.querySelectorAll('.cms-section')).toHaveLength(3);
 expect(rendered.container.querySelectorAll('.cms-hidden-draft')).toHaveLength(1);
 const sections=rendered.container.querySelectorAll<HTMLElement>('.cms-section'),transfer={effectAllowed:'move',setData:vi.fn(),getData:vi.fn()};
 fireEvent.dragStart(screen.getAllByRole('button',{name:/Drag .* section to reorder/})[2],{dataTransfer:transfer});
 const draggedKey=transfer.setData.mock.calls[0][1];transfer.getData.mockReturnValue(draggedKey);fireEvent.dragOver(sections[0],{dataTransfer:transfer});fireEvent.drop(sections[0],{dataTransfer:transfer});
 fireEvent.click(saveButton);
 await waitFor(()=>expect(put).toHaveBeenCalledWith('/cms/pages/1/visual-draft',expect.objectContaining({lock_version:12,sections:expect.arrayContaining([expect.objectContaining({section_key:'hero-one',presentation:expect.objectContaining({responsive:expect.objectContaining({mobile:expect.objectContaining({background:'wine',layout:'grid',columns:'2'})})})}),expect.objectContaining({is_visible:false})])})));
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);fireEvent.click(screen.getByRole('button',{name:'Delete'}));expect(rendered.container.querySelectorAll('.cms-section')).toHaveLength(3);confirm.mockReturnValue(true);fireEvent.click(screen.getByRole('button',{name:'Delete'}));expect(rendered.container.querySelectorAll('.cms-section')).toHaveLength(2);fireEvent.click(screen.getByRole('button',{name:'Undo'}));expect(rendered.container.querySelectorAll('.cms-section')).toHaveLength(3);confirm.mockRestore();
});

test('Add Section library exposes and inserts every required component in the actual page',async()=>{
 const anchor={id:10,section_key:'anchor',type:'text',sort_order:0,is_visible:true,content:{heading:'Existing page section',body:'Existing copy'},presentation:{}},draft={id:1,title:'Home',slug:'home',lock_version:20,sections:[anchor]};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections:[anchor]}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:{data:{data:[]}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:21,sections:payload.sections}}}) as any);
 const rendered=view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 const add=await screen.findByRole('button',{name:'Add Section'}),choices:[string,string][]=[['Hero','hero'],['Rich Text','text'],['Image','image'],['Text + Image','image_text'],['Cards','cards'],['Services','services'],['CTA','cta'],['Publications','publications'],['Career Timeline','career_timeline'],['Achievements','achievements'],['FAQ','faq'],['Gallery','gallery'],['Statistics','stats'],['Contact','contact'],['Appointment Widget','appointment'],['Video','video'],['Divider','divider'],['Spacer','spacer']];
 await waitFor(()=>expect(add).toBeEnabled());
 fireEvent.click(add);
 expect(screen.getByRole('heading',{name:'Choose a page component'})).toBeInTheDocument();
 choices.forEach(([label])=>expect(screen.getByRole('button',{name:`Add ${label} section`})).toBeInTheDocument());
 fireEvent.change(screen.getByLabelText('Search components'),{target:{value:'career'}});
 expect(screen.getByRole('button',{name:'Add Career Timeline section'})).toBeInTheDocument();
 expect(screen.queryByRole('button',{name:'Add Hero section'})).not.toBeInTheDocument();
 fireEvent.change(screen.getByLabelText('Search components'),{target:{value:''}});
 fireEvent.change(screen.getByLabelText('Insert location'),{target:{value:'start'}});
 fireEvent.click(screen.getByRole('button',{name:'Add Hero section'}));
 expect(rendered.container.querySelector('.cms-section')).toHaveClass('cms-hero');
 for(const [label,type] of choices.slice(1)){fireEvent.click(add);fireEvent.click(screen.getByRole('button',{name:`Add ${label} section`}));expect(rendered.container.querySelector(`.cms-${type}`)).toBeInTheDocument()}
 expect(rendered.container.querySelectorAll('.cms-section')).toHaveLength(19);
 fireEvent.click(screen.getByRole('button',{name:'Save Draft'}));
 await waitFor(()=>expect(put).toHaveBeenCalledTimes(1));
 const payload=put.mock.calls[0][1] as any;
 expect(payload.lock_version).toBe(20);
 expect(payload.sections.map((section:any)=>section.type)).toEqual(expect.arrayContaining(choices.map(([,type])=>type)));
 expect(payload.sections.every((section:any,index:number)=>section.sort_order===index)).toBe(true);
},30000);

test('nested components are selected, edited, reordered, duplicated, hidden, deleted, and saved from the page hierarchy',async()=>{
 const item=(key:string,fields:any)=>({key,is_visible:true,...fields}),sections=[
  {id:1,section_key:'cards-section',type:'cards',sort_order:0,is_visible:true,content:{heading:'Cards section',items:[item('00000000-0000-4000-8000-000000000001',{heading:'Card one',text:'Card text',url:''})]},presentation:{}},
  {id:2,section_key:'services-section',type:'services',sort_order:1,is_visible:true,content:{heading:'Services section',items:[item('00000000-0000-4000-8000-000000000002',{heading:'Service one',text:'Service text',url:''})]},presentation:{}},
  {id:3,section_key:'publications-section',type:'publications',sort_order:2,is_visible:true,content:{heading:'Publications section',items:[item('00000000-0000-4000-8000-000000000003',{title:'Paper one',meta:'Journal · 2026',url:''})]},presentation:{}},
  {id:4,section_key:'career-section',type:'career_timeline',sort_order:3,is_visible:true,content:{heading:'Career section',items:[item('00000000-0000-4000-8000-000000000004',{year:'2020',heading:'Milestone one',text:'Milestone text'})]},presentation:{}},
  {id:5,section_key:'achievements-section',type:'achievements',sort_order:4,is_visible:true,content:{heading:'Achievements section',items:[item('00000000-0000-4000-8000-000000000005',{value:'10+',heading:'Achievement one',text:'Achievement text'})]},presentation:{}},
  {id:6,section_key:'faq-section',type:'faq',sort_order:5,is_visible:true,content:{heading:'FAQ section',items:[item('00000000-0000-4000-8000-000000000006',{question:'Question one?',answer:'Answer one.'})]},presentation:{}},
  {id:7,section_key:'gallery-section',type:'gallery',sort_order:6,is_visible:true,content:{heading:'Gallery section',items:[item('00000000-0000-4000-8000-000000000007',{image_url:'',image_alt:'Gallery image',caption:'Gallery one'})]},presentation:{}},
  {id:8,section_key:'stats-section',type:'stats',sort_order:7,is_visible:true,content:{heading:'Statistics section',items:[item('00000000-0000-4000-8000-000000000008',{value:'1',label:'Stat one'})]},presentation:{}},
 ],draft={id:1,title:'Home',slug:'home',lock_version:30,sections};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:{data:{data:[]}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:31,sections:payload.sections}}}) as any);
 const rendered=view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 await waitFor(()=>expect(screen.getByRole('button',{name:'Save Draft'})).toBeEnabled());
 const schemas:[string,string][]=[['Select Card one component','Card heading'],['Select Service one component','Service heading'],['Select Paper one component','Publication title'],['Select 2020: Milestone one component','Year or period'],['Select Achievement one component','Achievement value'],['Select Question one? component','Question'],['Select Gallery one component','Image URL'],['Select 1 Stat one component','Statistic value']];
 for(const [control,field] of schemas){fireEvent.click(screen.getByRole('button',{name:control}));expect(screen.getByLabelText(field)).toBeInTheDocument()}
 fireEvent.click(screen.getByRole('button',{name:'Select Card one component'}));
 fireEvent.focus(screen.getByLabelText('Card heading'));
 await waitFor(()=>expect(screen.getByRole('toolbar',{name:'Website editor'})).toHaveTextContent('Page > Cards > Card one > Card heading'));
 fireEvent.change(screen.getByLabelText('Card heading'),{target:{value:'Updated card'}});
 expect(rendered.container.querySelector('.cms-cards .cms-card-grid h3')).toHaveTextContent('Updated card');
 fireEvent.click(screen.getByRole('button',{name:'Done'}));
 fireEvent.click(screen.getByRole('button',{name:'Add Cards item'}));
 expect(rendered.container.querySelectorAll('.cms-cards .cms-card-grid .cms-editable-component')).toHaveLength(2);
 fireEvent.click(screen.getByRole('button',{name:'Move earlier'}));
 expect(rendered.container.querySelector('.cms-cards .cms-card-grid h3')).toHaveTextContent('New card');
 fireEvent.click(screen.getByRole('button',{name:'Duplicate'}));
 expect(rendered.container.querySelectorAll('.cms-cards .cms-card-grid .cms-editable-component')).toHaveLength(3);
 fireEvent.click(screen.getByRole('button',{name:'Hide'}));
 expect(rendered.container.querySelectorAll('.cms-component-hidden')).toHaveLength(1);
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);
 fireEvent.click(screen.getByRole('button',{name:'Delete component'}));
 expect(rendered.container.querySelectorAll('.cms-cards .cms-card-grid .cms-editable-component')).toHaveLength(3);
 confirm.mockReturnValue(true);fireEvent.click(screen.getByRole('button',{name:'Delete component'}));
 expect(rendered.container.querySelectorAll('.cms-cards .cms-card-grid .cms-editable-component')).toHaveLength(2);
 fireEvent.click(screen.getByRole('button',{name:'Undo'}));
 expect(rendered.container.querySelectorAll('.cms-cards .cms-card-grid .cms-editable-component')).toHaveLength(3);
 confirm.mockRestore();
 fireEvent.click(screen.getByRole('button',{name:'Save Draft'}));
 await waitFor(()=>expect(put).toHaveBeenCalledTimes(1));
 const payload=put.mock.calls[0][1] as any,cardItems=payload.sections.find((section:any)=>section.type==='cards').content.items;
 expect(cardItems).toHaveLength(3);expect(cardItems.some((entry:any)=>entry.heading==='Updated card')).toBe(true);expect(cardItems.some((entry:any)=>entry.is_visible===false)).toBe(true);expect(new Set(cardItems.map((entry:any)=>entry.key)).size).toBe(3);
},30000);

test('an exact rendered image is replaced from the persistent library and styled live before atomic save',async()=>{
 const section={id:10,section_key:'feature-image',type:'image',sort_order:0,is_visible:true,content:{heading:'Care environment',image_media_id:'old-image',image_url:'',image_alt:'Old consultation room',image_is_decorative:false,caption:'Old caption',image_link:''},presentation:{}};
 const draft={id:1,title:'Home',slug:'home',lock_version:40,sections:[section]},asset={id:'new-image',title:'Welcoming consultation room',original_name:'room.webp',url:'/media/new-image',alt_text:'A welcoming private consultation room',caption:'Care setting',is_decorative:false,width_pixels:1600,height_pixels:900,mime_type:'image/webp',size_bytes:245760};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections:[section]}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:url==='/cms/media'?{data:{data:[asset]}} as any:{data:{data:[]}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:41,sections:payload.sections}}}) as any);
 const rendered=view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 await waitFor(()=>expect(screen.getByRole('button',{name:'Save Draft'})).toBeEnabled());
 fireEvent.click(await screen.findByRole('button',{name:'Edit standalone image'}));
 expect(screen.getByRole('complementary',{name:'Image controls'})).toHaveTextContent('Page › Image › Image');
 fireEvent.click(screen.getByRole('button',{name:'Replace image'}));
 expect(await screen.findByRole('heading',{name:'Choose or upload an image'})).toBeInTheDocument();
 fireEvent.change(screen.getByLabelText('Search media'),{target:{value:'consultation'}});
 fireEvent.click(await screen.findByRole('button',{name:'Use image: Welcoming consultation room'}));
 fireEvent.change(screen.getByLabelText('Alternative text'),{target:{value:'Doctor speaking with a patient in a private room'}});
 fireEvent.change(screen.getByLabelText('Caption'),{target:{value:'A calm, confidential care setting'}});
 fireEvent.change(screen.getByLabelText('Image link'),{target:{value:'/contact'}});
 fireEvent.change(screen.getByLabelText('Crop / focus'),{target:{value:'bottom_right'}});
 fireEvent.change(screen.getByLabelText('Width'),{target:{value:'large'}});
 fireEvent.change(screen.getByLabelText('Height'),{target:{value:'medium'}});
 fireEvent.change(screen.getByLabelText('Alignment'),{target:{value:'center'}});
 fireEvent.change(screen.getByLabelText('Object fit'),{target:{value:'contain'}});
 fireEvent.change(screen.getByLabelText('Corner radius'),{target:{value:'round'}});
 fireEvent.change(screen.getByLabelText('Overlay'),{target:{value:'wine'}});
 fireEvent.change(screen.getByLabelText('Overlay opacity'),{target:{value:'40'}});
 fireEvent.change(screen.getByLabelText('Image opacity'),{target:{value:'80'}});
 const image=rendered.container.querySelector<HTMLImageElement>('.cms-image-only img')!;
 expect(image).toHaveAttribute('src','/media/new-image');
 expect(image).toHaveAttribute('alt','Doctor speaking with a patient in a private room');
 expect(image).toHaveStyle({height:'24rem',objectFit:'contain',objectPosition:'right bottom',opacity:'0.8'});
 expect(image.closest('.cms-image-frame')).toHaveStyle({width:'78%',borderRadius:'50%'});
 expect(rendered.container.querySelector('.cms-image-overlay')).toHaveStyle({background:'rgba(111,24,56,0.4)'});
 expect(rendered.container.querySelector('.cms-image-only figcaption')).toHaveTextContent('A calm, confidential care setting');
 fireEvent.click(screen.getByRole('button',{name:'Save Draft'}));
 await waitFor(()=>expect(put).toHaveBeenCalledWith('/cms/pages/1/visual-draft',expect.objectContaining({lock_version:40,sections:[expect.objectContaining({content:expect.objectContaining({image_media_id:'new-image',image_url:'',image_alt:'Doctor speaking with a patient in a private room',image_is_decorative:false,caption:'A calm, confidential care setting',image_link:'/contact'}),presentation:expect.objectContaining({responsive:expect.objectContaining({desktop:expect.objectContaining({crop_position:'bottom_right',image_width:'large',image_height:'medium',image_alignment:'center',image_fit:'contain',image_radius:'round',image_overlay_color:'wine',image_overlay_opacity:'40',image_opacity:'80'})})})})]})));
},30000);

test('image upload failure retains the chosen file metadata and a retry selects the scanned asset',async()=>{
 const section={id:10,section_key:'feature-image',type:'image',sort_order:0,is_visible:true,content:{heading:'Featured image',image_url:'',image_alt:'',image_is_decorative:false,caption:'',image_link:''},presentation:{}},draft={id:1,title:'Home',slug:'home',lock_version:50,sections:[section]},asset={id:'uploaded-image',title:'Clinical team',original_name:'team.png',url:'/media/uploaded-image',alt_text:'The specialist clinical team',caption:null,is_decorative:false,width_pixels:1200,height_pixels:800,mime_type:'image/png',size_bytes:120000};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections:[section]}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:url==='/cms/media'?{data:{data:[]}} as any:{data:{data:[]}} as any);
 post.mockRejectedValueOnce({response:{data:{message:'The image could not pass the safety scan.'}}}).mockResolvedValueOnce({data:{data:asset}} as any);
 view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 await waitFor(()=>expect(screen.getByRole('button',{name:'Save Draft'})).toBeEnabled());
 fireEvent.click(await screen.findByRole('button',{name:'Edit standalone image'}));
 fireEvent.click(screen.getByRole('button',{name:'Replace image'}));
 const file=new File(['approved-image-bytes'],'team.png',{type:'image/png'});
 fireEvent.change(screen.getByLabelText('Image file'),{target:{files:[file]}});
 fireEvent.change(screen.getByLabelText('Alternative text'),{target:{value:'The specialist clinical team'}});
 await waitFor(()=>expect(screen.getByLabelText('Media title')).toHaveValue('team'));
 fireEvent.change(screen.getByLabelText('Media title'),{target:{value:'Clinical team'}});
 await waitFor(()=>expect(screen.getByRole('button',{name:'Upload, scan, and use'})).toBeEnabled());
 fireEvent.submit(screen.getByRole('button',{name:'Upload, scan, and use'}).closest('form')!);
 await waitFor(()=>expect(post).toHaveBeenCalledTimes(1));
 expect(await screen.findByRole('alert')).toHaveTextContent('could not pass the safety scan');
 expect(screen.getByLabelText('Media title')).toHaveValue('Clinical team');
 expect(screen.getByLabelText('Alternative text')).toHaveValue('The specialist clinical team');
 expect((screen.getByLabelText('Image file') as HTMLInputElement).files?.[0]).toBe(file);
 fireEvent.submit(screen.getByRole('button',{name:'Upload, scan, and use'}).closest('form')!);
 await waitFor(()=>expect(post).toHaveBeenCalledTimes(2));
 await waitFor(()=>expect(screen.queryByRole('heading',{name:'Choose or upload an image'})).not.toBeInTheDocument());
 expect(screen.getByRole('img',{name:'The specialist clinical team'})).toHaveAttribute('src','/media/uploaded-image');
 expect(post).toHaveBeenLastCalledWith('/cms/media',expect.any(FormData));
},30000);

test('a section background uses the same media library, restores focus after Escape, and saves a stable asset reference',async()=>{
 const section={id:10,section_key:'copy-background',type:'text',sort_order:0,is_visible:true,content:{heading:'Support and care',body:'Trusted information'},presentation:{}},draft={id:1,title:'Home',slug:'home',lock_version:60,sections:[section]},asset={id:'background-image',title:'Quiet practice texture',original_name:'practice-texture.webp',url:'/media/background-image',alt_text:null,caption:null,is_decorative:true,width_pixels:1920,height_pixels:1080,mime_type:'image/webp',size_bytes:310000};
 get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:url==='/cms/public-settings'?{data:{data:{}}} as any:url==='/content/pages/home'?{data:{data:{title:'Home',sections:[section]}}} as any:url==='/cms/pages'?{data:{data:[{id:1,slug:'home'}]}} as any:url==='/cms/pages/1'?{data:{data:draft}} as any:url==='/cms/media'?{data:{data:[asset]}} as any:{data:{data:[]}} as any);
 put.mockImplementation(async(_url:string,payload:any)=>({data:{data:{...draft,lock_version:61,sections:payload.sections}}}) as any);
 const rendered=view(<Layout><CmsPublicPage slug="home"/></Layout>,'/');
 fireEvent.click(await screen.findByRole('button',{name:'Edit site'}));
 await waitFor(()=>expect(screen.getByRole('button',{name:'Save Draft'})).toBeEnabled());
 fireEvent.click(screen.getByRole('button',{name:'Edit text section properties'}));
 const choose=screen.getByRole('button',{name:'Choose from media library'});
 fireEvent.click(choose);
 expect(await screen.findByText('practice-texture.webp · WEBP')).toBeInTheDocument();
 fireEvent.keyDown(screen.getByLabelText('Search media'),{key:'Escape'});
 await waitFor(()=>expect(screen.getByRole('button',{name:'Choose from media library'})).toHaveFocus());
 fireEvent.click(screen.getByRole('button',{name:'Choose from media library'}));
 fireEvent.click(await screen.findByRole('button',{name:'Use image: Quiet practice texture'}));
 expect(rendered.container.querySelector<HTMLElement>('.cms-text')?.style.backgroundImage).toContain('/media/background-image');
 await waitFor(()=>expect(screen.getByRole('button',{name:'Replace library background'})).toHaveFocus());
 fireEvent.click(screen.getByRole('button',{name:'Save Draft'}));
 await waitFor(()=>expect(put).toHaveBeenCalledWith('/cms/pages/1/visual-draft',expect.objectContaining({lock_version:60,sections:[expect.objectContaining({presentation:expect.objectContaining({responsive:expect.objectContaining({desktop:expect.objectContaining({background_media_id:'background-image',background_image:''})})})})]})));
},30000);
