import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { fireEvent,render,screen,waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach,expect,test,vi } from 'vitest';
import { Layout } from '../App';import StaffDashboardPage from './StaffDashboardPage';import CmsEditorPage from './CmsEditorPage';import { api } from '../api';
vi.mock('../api',()=>({api:{get:vi.fn(),post:vi.fn(),put:vi.fn(),patch:vi.fn(),delete:vi.fn()}}));
const get=vi.mocked(api.get),put=vi.mocked(api.put),post=vi.mocked(api.post);
function view(node:React.ReactNode,path='/staff'){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[path]}>{node}</MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{get.mockReset();put.mockReset();post.mockReset();put.mockResolvedValue({data:{}} as any);post.mockResolvedValue({data:{}} as any)});
test('Power Admin dashboard exposes working operational and publishing links',async()=>{get.mockImplementation(async(url:string)=>url==='/staff/dashboard'?{data:{role:'power_admin',metrics:{today:0,pending:0,online_today:0,unclaimed_patients:0},pending_requests:[],today_appointments:[]}} as any:{data:{data:[]}} as any);view(<StaffDashboardPage/>);expect(await screen.findByRole('link',{name:/Website pages/})).toHaveAttribute('href','/staff/cms');expect(screen.getByRole('link',{name:/Publications/})).toHaveAttribute('href','/staff/research-review');expect(screen.getByRole('link',{name:/Education/})).toHaveAttribute('href','/staff/education');expect(screen.getByRole('link',{name:/Audit log/})).toHaveAttribute('href','/staff/audit');expect(screen.getByRole('link',{name:/Appointments/})).toHaveAttribute('href','/staff/calendar');});
test('ordinary staff do not receive Power Admin publishing links',async()=>{get.mockResolvedValue({data:{role:'admin',metrics:{today:0,pending:0,online_today:0,unclaimed_patients:0},pending_requests:[],today_appointments:[]}} as any);view(<StaffDashboardPage/>);await screen.findByRole('heading',{name:'Practice today'});expect(screen.queryByRole('link',{name:/Website pages/})).not.toBeInTheDocument();expect(screen.getByRole('link',{name:/Inbox/})).toHaveAttribute('href','/staff/inbox');});
test('public site provides an authenticated Power Admin edit toggle',async()=>{get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:{role:'power_admin'}}} as any:{data:{data:{}}} as any);view(<Layout><h1>Public page</h1></Layout>,'/research');const toggle=await screen.findByRole('button',{name:'Edit site'});fireEvent.click(toggle);expect(screen.getByRole('navigation',{name:'Power Admin editing tools'})).toBeInTheDocument();expect(screen.getByRole('link',{name:/Edit this area/})).toHaveAttribute('href','/staff/cms?slug=research');});
test('published navigation and theme settings drive the public layout',async()=>{get.mockImplementation(async(url:string)=>url==='/me'?{data:{user:null}} as any:{data:{data:{navigation:[{label:'Care options',path:'/services'},{label:'Start here',path:'/book'}],theme:{palette:'plum',density:'compact',heading_style:'modern'}}}} as any);const rendered=view(<Layout><h1>Public page</h1></Layout>);expect(await screen.findByRole('link',{name:'Care options'})).toHaveAttribute('href','/services');expect(screen.getByRole('link',{name:'Start here'})).toHaveAttribute('href','/book');expect(screen.queryByRole('link',{name:'About'})).not.toBeInTheDocument();expect(rendered.container.querySelector('.site-shell')).toHaveClass('theme-plum','density-compact','headings-modern');});
test('collapsed navigation exposes accurate accessible state',async()=>{get.mockResolvedValue({data:{}} as any);view(<Layout><h1>Public page</h1></Layout>);const toggle=screen.getByRole('button',{name:'Open navigation'});expect(toggle).toHaveAttribute('aria-expanded','false');fireEvent.click(toggle);expect(screen.getByRole('button',{name:'Close navigation'})).toHaveAttribute('aria-expanded','true');expect(document.getElementById('main-navigation-links')).toHaveClass('show');});
test('website editor offers an explicit existing-page dropdown',async()=>{get.mockImplementation(async(url:string)=>url==='/cms/pages'?{data:{data:[{id:1,title:'About the practice',slug:'about-practice',status:'draft'},{id:2,title:'Patient guide',slug:'patient-guide',status:'published'}]}} as any:{data:{data:{id:1,title:'About the practice',slug:'about-practice',sections:[]}}} as any);view(<CmsEditorPage/>,'/staff/cms');const picker=await screen.findByRole('combobox',{name:'Choose an existing page'});await waitFor(()=>expect(picker).toHaveValue('1'));expect(screen.getByRole('option',{name:'Patient guide — /patient-guide (published)'})).toBeInTheDocument();fireEvent.change(picker,{target:{value:'2'}});expect(picker).toHaveValue('2');});
test('website editor exposes structured content presentation visibility and version controls',async()=>{get.mockImplementation(async(url:string)=>{if(url==='/cms/pages')return{data:{data:[{id:1,title:'Home',slug:'home',status:'published'}]}} as any;if(url==='/cms/pages/1')return{data:{data:{id:1,title:'Home',slug:'home',template:'landing',status:'published',sections:[{id:10,section_key:'hero-one',type:'hero',is_visible:true,content:{eyebrow:'Care',heading:'Whole-person care',text:'Introduction',primary_label:'Book',primary_url:'/book'},presentation:{background:'ivory',alignment:'left',width:'normal',spacing:'normal'}}]}}} as any;if(url==='/cms/pages/1/versions')return{data:{data:[{id:4,version:2,reason:'Section updated',created_at:'2026-08-28T10:00:00Z'}]}} as any;return{data:{data:{}}} as any});view(<CmsEditorPage/>,'/staff/cms?slug=home');expect(await screen.findByDisplayValue('Whole-person care')).toBeInTheDocument();expect(screen.getByLabelText('Primary button label')).toHaveValue('Book');expect(screen.getByLabelText('Background')).toHaveValue('ivory');expect(screen.getByLabelText(/Show this section/)).toBeChecked();fireEvent.click(screen.getByText('Version history'));expect(screen.getByRole('button',{name:/Restore as draft/})).toBeInTheDocument();});
test('website settings distinguish private draft from explicit publish',async()=>{get.mockImplementation(async(url:string)=>url==='/cms/pages'?{data:{data:[]}} as any:url==='/cms/settings'?{data:{data:{navigation:{draft_value:[{label:'Home',path:'/'}]},theme:{draft_value:{palette:'wine',density:'comfortable',heading_style:'editorial'}}}}} as any:{data:{data:[]}} as any);view(<CmsEditorPage/>,'/staff/cms');fireEvent.click(await screen.findByRole('button',{name:/Navigation & theme/}));expect(screen.getByRole('heading',{name:'Navigation & theme'})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Colour palette'),{target:{value:'plum'}});fireEvent.click(screen.getByRole('button',{name:/Save private draft/}));await waitFor(()=>expect(put).toHaveBeenCalledTimes(2));expect(post).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:/Save & publish/}));await waitFor(()=>expect(post).toHaveBeenCalledWith('/cms/settings/navigation/publish'));expect(post).toHaveBeenCalledWith('/cms/settings/theme/publish');});
