import { useQuery } from '@tanstack/react-query';
import { ArrowLeft,History,Search } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';

export default function AuditLogPage(){
 const [action,setAction]=useState(''),[actor,setActor]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1);
 const q=useQuery({queryKey:['audit-logs',action,actor,from,to,page],queryFn:async()=>(await api.get('/cms/audit-logs',{params:{action:action||undefined,actor_id:actor||undefined,from:from||undefined,to:to||undefined,page}})).data,retry:false});
 if(q.isError)return <section className="portal-guest"><h1>Power Admin access required.</h1><Link className="btn btn-primary" to="/sign-in">Sign in</Link></section>;
 return <main className="staff-main management-page"><header><div><span className="eyebrow">Security & accountability</span><h1>Audit log</h1><p>Review privacy-filtered administrative changes within a bounded date range.</p></div><Link className="btn btn-outline-primary" to="/staff"><ArrowLeft/> Dashboard</Link></header><section className="staff-card"><div className="audit-filters"><label><span><Search/> Action starts with</span><input className="form-control" value={action} onChange={e=>{setAction(e.target.value);setPage(1)}} placeholder="For example: identity."/></label><label>Actor ID<input className="form-control" inputMode="numeric" value={actor} onChange={e=>{setActor(e.target.value);setPage(1)}}/></label><label>From<input className="form-control" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label>To<input className="form-control" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label></div>{q.isLoading?<p role="status">Loading activity…</p>:q.data?.data?.length?q.data.data.map((log:any)=><article className="audit-row" key={log.id}><History/><div><h2>{log.action}</h2><p>{log.actor?.name??'System'} · {log.subject_type} #{log.subject_id??'—'}</p>{log.metadata?.fields?.length>0&&<small>Changed: {log.metadata.fields.join(', ')}</small>}</div><time>{new Date(log.created_at).toLocaleString('en-NG')}</time></article>):<div className="staff-empty"><History/><p>No matching activity in this period.</p></div>}<div className="pagination-actions"><button disabled={(q.data?.current_page??1)<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {q.data?.current_page??page} of {q.data?.last_page??1}</span><button disabled={(q.data?.current_page??1)>=(q.data?.last_page??1)} onClick={()=>setPage(value=>value+1)}>Next</button></div></section></main>
}
