import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useSearchParams } from 'react-router-dom';
import { ArrowRight, HeartPulse, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { api, prepareSession } from '../api';

export function SignInPage() {
  const navigate=useNavigate(); const [form,setForm]=useState({email:'',password:'',remember:false}),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await prepareSession();const {data}=await api.post('/auth/login',form);navigate(data.user.role==='patient'?'/portal':'/staff')}catch(e:any){setError(e.response?.data?.errors?.email?.[0]||'We could not sign you in. Please check your details.')}finally{setLoading(false)}};
  return <AuthShell title="Welcome back" intro="Sign in to manage your appointments and practice communication."><form onSubmit={submit}><label className="form-label" htmlFor="sign-in-email">Email address</label><div className="field-icon"><Mail/><input id="sign-in-email" className="form-control" type="email" autoComplete="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><label className="form-label mt-3" htmlFor="sign-in-password">Password</label><div className="field-icon"><LockKeyhole/><input id="sign-in-password" className="form-control" type="password" autoComplete="current-password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><div className="auth-options"><label><input type="checkbox" checked={form.remember} onChange={e=>setForm({...form,remember:e.target.checked})}/> Keep me signed in</label><Link to="/forgot-password">Forgot password?</Link></div>{error&&<div className="alert alert-danger" role="alert">{error}</div>}<button disabled={loading} className="btn btn-primary btn-lg w-100">{loading?'Signing in…':'Sign in'} <ArrowRight/></button><p className="auth-switch">New to the portal? <Link to="/register">Create a patient account</Link></p></form></AuthShell>;
}

export function RegisterPage(){const navigate=useNavigate();const [form,setForm]=useState({name:'',email:'',phone:'',password:'',password_confirmation:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await prepareSession();await api.post('/auth/register',form);navigate('/portal')}catch(e:any){const errors=e.response?.data?.errors;setError(errors?Object.values(errors).flat().join(' '):'We could not create your account.')}finally{setLoading(false)}};return <AuthShell title="Create your patient account" intro="A secure place for appointments, consultation links and practice updates."><form onSubmit={submit}><div className="row g-3"><div className="col-12"><label className="form-label" htmlFor="register-name">Full name</label><input id="register-name" required className="form-control" autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="col-md-6"><label className="form-label" htmlFor="register-email">Email</label><input id="register-email" required type="email" className="form-control" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="col-md-6"><label className="form-label" htmlFor="register-phone">Phone</label><input id="register-phone" required className="form-control" autoComplete="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="col-md-6"><label className="form-label" htmlFor="register-password">Password</label><input id="register-password" required type="password" className="form-control" autoComplete="new-password" aria-describedby="password-help" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><div className="col-md-6"><label className="form-label" htmlFor="register-password-confirmation">Confirm password</label><input id="register-password-confirmation" required type="password" className="form-control" autoComplete="new-password" aria-describedby="password-help" value={form.password_confirmation} onChange={e=>setForm({...form,password_confirmation:e.target.value})}/></div></div><p id="password-help" className="password-help">Use at least 10 characters with upper and lowercase letters, a number and a symbol.</p>{error&&<div className="alert alert-danger" role="alert">{error}</div>}<button disabled={loading} className="btn btn-primary btn-lg w-100">{loading?'Creating account…':'Create secure account'} <ArrowRight/></button><p className="auth-switch">Already registered? <Link to="/sign-in">Sign in</Link></p></form></AuthShell>}

export function ForgotPasswordPage(){const [email,setEmail]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await prepareSession();const {data}=await api.post('/auth/forgot-password',{email});setMessage(data.message)}catch(requestError:any){setError(requestError?.response?.data?.message||'We could not send reset instructions. Your email is still here so you can try again.')}finally{setLoading(false)}};return <AuthShell title="Reset your password" intro="Enter your email address and we’ll send reset instructions if an account exists.">{message?<div className="notice" role="status"><Mail/><p>{message}</p></div>:<form onSubmit={submit}><label className="form-label" htmlFor="forgot-email">Email address</label><input id="forgot-email" required type="email" className="form-control" value={email} onChange={e=>setEmail(e.target.value)}/>{error&&<div className="alert alert-danger mt-3" role="alert">{error}</div>}<button disabled={loading} className="btn btn-primary btn-lg w-100 mt-4">{loading?'Sending…':'Send reset instructions'}</button><p className="auth-switch"><Link to="/sign-in">Return to sign in</Link></p></form>}</AuthShell>}

export function ResetPasswordPage(){const [params]=useSearchParams(),navigate=useNavigate();const [form,setForm]=useState({email:params.get('email')??'',token:params.get('token')??'',password:'',password_confirmation:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await prepareSession();await api.post('/auth/reset-password',form);navigate('/sign-in')}catch(e:any){setError(e.response?.data?.message??'This reset link is invalid or expired.')}finally{setLoading(false)}};return <AuthShell title="Choose a new password" intro="Create a strong, unique password for your patient account."><form onSubmit={submit}><label className="form-label" htmlFor="reset-email">Email</label><input id="reset-email" required type="email" className="form-control" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><label className="form-label mt-3" htmlFor="reset-password">New password</label><input id="reset-password" required type="password" className="form-control" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><label className="form-label mt-3" htmlFor="reset-password-confirmation">Confirm new password</label><input id="reset-password-confirmation" required type="password" className="form-control" value={form.password_confirmation} onChange={e=>setForm({...form,password_confirmation:e.target.value})}/>{error&&<div className="alert alert-danger mt-3" role="alert">{error}</div>}<button disabled={loading} className="btn btn-primary btn-lg w-100 mt-4">{loading?'Resetting…':'Reset password'}</button></form></AuthShell>}

function AuthShell({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <section className="auth-page"><div className="auth-panel"><Link className="auth-logo" to="/"><HeartPulse/> Breast Oncology Practice</Link><span className="eyebrow">Patient portal</span><h1>{title}</h1><p>{intro}</p>{children}</div><aside><div><ShieldCheck/><h2>Private by design.</h2><p>Your account information and appointment details are protected by access controls designed for a medical practice.</p></div><small>This portal is not an emergency service.</small></aside></section>}
