import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, FileCheck2, LockKeyhole, Paperclip, Video } from 'lucide-react';
import type { Service, Slot } from '../types';

type Form = { service_id: string; consultation_method: 'in_person'|'online'; date: string; starts_at: string; name: string; email: string; phone: string; reason: string };
const initial: Form = { service_id:'', consultation_method:'in_person', date:'', starts_at:'', name:'', email:'', phone:'', reason:'' };

export default function BookingPage({services}:{services:Service[]}) {
  const [step,setStep]=useState(1), [form,setForm]=useState(initial), [slots,setSlots]=useState<Slot[]>([]), [attachment,setAttachment]=useState<File|null>(null), [loading,setLoading]=useState(false), [error,setError]=useState(''), [reference,setReference]=useState('');
  const requestId=useRef(globalThis.crypto?.randomUUID?.() ?? `00000000-0000-4000-8000-${Math.random().toString(16).slice(2).padEnd(12,'0').slice(0,12)}`);
  const chosen=services.find(s=>String(s.id)===form.service_id);
  useEffect(()=>{ if(!form.date||!form.service_id)return; setLoading(true); setError(''); fetch(`/api/availability/${form.service_id}?date=${form.date}&method=${form.consultation_method}`).then(r=>r.json()).then(j=>setSlots(j.data??[])).catch(()=>setError('We could not load available times. Please try again.')).finally(()=>setLoading(false)); },[form.date,form.service_id,form.consultation_method]);
  const update=(key:keyof Form,value:string)=>setForm(v=>({...v,[key]:value}));
  const next=()=>{setError(''); if(step===1&&!form.service_id)return setError('Please choose a consultation service.'); if(step===2&&!form.starts_at)return setError('Please choose an available time.'); setStep(s=>s+1)};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const payload=new FormData();Object.entries(form).forEach(([key,value])=>{if(key!=='date')payload.append(key,value)});payload.append('client_request_id',requestId.current);if(attachment)payload.append('attachment',attachment);const r=await fetch('/api/appointment-requests',{method:'POST',headers:{'Accept':'application/json'},body:payload});const j=await r.json();if(!r.ok)throw new Error(j.message||Object.values(j.errors??{}).flat()[0]||'Unable to submit request.');setReference(j.reference);setStep(4)}catch(e){setError(e instanceof Error?e.message:'Unable to submit request.')}finally{setLoading(false)}};
  return <><section className="booking-hero"><div className="container"><span className="eyebrow">Appointments</span><h1>Let’s find the right care for you.</h1><p>Request a convenient time in a few simple steps. A team member will confirm the appointment.</p></div></section><section className="booking-section"><div className="container"><div className="booking-shell"><div className="booking-progress">{[1,2,3].map((n)=><div className={step>=n?'active':''} key={n}><span>{step>n?<Check/>:n}</span><small>{['Consultation','Date & time','Your details'][n-1]}</small></div>)}</div><div className="booking-body">
  {step===1&&<div><span className="step-label">Step 1 of 3</span><h2>What can we help with?</h2><p className="step-intro">Select the option that feels closest. The practice can adjust it after review.</p><div className="service-options">{services.map(s=><button type="button" key={s.id} onClick={()=>update('service_id',String(s.id))} className={form.service_id===String(s.id)?'selected':''}><span className="radio-dot"/><div><b>{s.name}</b><small>{s.summary}</small><em><Clock3/> {s.duration_minutes} min {s.online_available&&'· Online option'}</em></div></button>)}</div><div className="method-choice"><label><input type="radio" checked={form.consultation_method==='in_person'} onChange={()=>update('consultation_method','in_person')}/> In-person consultation</label><label className={!chosen?.online_available?'disabled':''}><input type="radio" disabled={!chosen?.online_available} checked={form.consultation_method==='online'} onChange={()=>update('consultation_method','online')}/> <Video/> Online consultation</label></div></div>}
  {step===2&&<div><button type="button" className="back" onClick={()=>setStep(1)}><ArrowLeft/> Back</button><span className="step-label">Step 2 of 3</span><h2>Choose a date and time.</h2><label className="form-label mt-4" htmlFor="date">Preferred date</label><input id="date" className="form-control form-control-lg date-input" type="date" min={new Date().toISOString().slice(0,10)} value={form.date} onChange={e=>{update('date',e.target.value);update('starts_at','')}}/><div className="slot-grid">{loading?<p>Finding available times…</p>:slots.map(slot=><button type="button" className={form.starts_at===slot.starts_at?'selected':''} key={slot.starts_at} onClick={()=>update('starts_at',slot.starts_at)}>{slot.label}</button>)}</div>{form.date&&!loading&&!slots.length&&<div className="empty-inline"><CalendarDays/><p>No available times on this date. Please choose another day.</p></div>}</div>}
  {step===3&&<form onSubmit={submit}><button type="button" className="back" onClick={()=>setStep(2)}><ArrowLeft/> Back</button><span className="step-label">Step 3 of 3</span><h2>Tell us how to reach you.</h2><div className="summary-card"><b>{chosen?.name}</b><span>{form.starts_at&&new Date(form.starts_at).toLocaleString('en-NG',{dateStyle:'full',timeStyle:'short'})}</span><small>{form.consultation_method==='online'?'Online consultation':'In-person consultation'}</small></div><div className="row g-3"><div className="col-md-6"><label className="form-label" htmlFor="booking-name">Full name</label><input id="booking-name" required autoComplete="name" className="form-control" value={form.name} onChange={e=>update('name',e.target.value)}/></div><div className="col-md-6"><label className="form-label" htmlFor="booking-phone">Phone</label><input id="booking-phone" required autoComplete="tel" inputMode="tel" className="form-control" value={form.phone} onChange={e=>update('phone',e.target.value)}/></div><div className="col-12"><label className="form-label" htmlFor="booking-email">Email</label><input id="booking-email" required autoComplete="email" type="email" className="form-control" value={form.email} onChange={e=>update('email',e.target.value)}/></div><div className="col-12"><label className="form-label" htmlFor="booking-reason">Reason for appointment</label><textarea id="booking-reason" required minLength={10} className="form-control" rows={4} placeholder="Briefly describe your concern (please do not include unnecessary sensitive details)." value={form.reason} onChange={e=>update('reason',e.target.value)}/></div><div className="col-12"><div className="booking-attachment"><div><Paperclip/><label className="form-label" htmlFor="booking-attachment">Attach a document <span>(optional)</span></label><p id="booking-attachment-help">PDF, JPG or PNG only, up to 10 MB. Your file is security-scanned and stored privately with this appointment.</p></div><input id="booking-attachment" className="form-control" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" aria-describedby="booking-attachment-help" onChange={e=>setAttachment(e.target.files?.[0]??null)}/>{attachment&&<p className="attachment-selected" role="status"><FileCheck2/> Selected: {attachment.name}</p>}</div></div></div><p className="privacy-note"><LockKeyhole/> Your information is sent securely and used only to manage your care request.</p>{loading&&<div className="upload-progress" role="status" aria-live="polite"><span/> {attachment?'Scanning and securely sending your request…':'Securely sending your request…'}</div>}<button disabled={loading} className="btn btn-primary btn-lg w-100">{loading?'Please wait…':'Send appointment request'} <ArrowRight/></button></form>}
  {step===4&&<div className="success"><div><Check/></div><span className="eyebrow">Request received</span><h2>Thank you, {form.name.split(' ')[0]}.</h2><p>The practice team will review your request and contact you to confirm the appointment.</p>{attachment&&<p className="attachment-selected"><FileCheck2/> Your attachment was scanned and stored securely.</p>}<small>Your private reference</small><code>{reference}</code><a href="/" className="btn btn-outline-primary">Return home</a></div>}
  {error&&<div className="alert alert-danger mt-4" role="alert">{error}</div>}{step<3&&<button className="btn btn-primary btn-lg continue" onClick={next}>Continue <ArrowRight/></button>}</div><aside><LockKeyhole/><h3>Your privacy matters.</h3><p>Only information needed to arrange this consultation is collected here. Clinical details remain private.</p><hr/><b>Need urgent help?</b><p>This booking form is not monitored for emergencies. Please use local emergency services when immediate care is needed.</p></aside></div></div></section></>;
}
