import { useQuery,useQueryClient } from '@tanstack/react-query';
import { ArrowDown,ArrowLeft,ArrowUp,Eye,FilePlus2,Plus,Send,Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect,useState } from 'react';
import { api } from '../api';

export default function CmsEditorPage(){
 const qc=useQueryClient(),[selected,setSelected]=useState<number|null>(null),[message,setMessage]=useState('');
 const pages=useQuery({queryKey:['cms-pages'],queryFn:async()=>(await api.get('/cms/pages')).data.data,retry:false});
 const page=useQuery({queryKey:['cms-page',selected],queryFn:async()=>(await api.get(`/cms/pages/${selected}`)).data.data,enabled:!!selected});
 useEffect(()=>{if(!selected&&pages.data?.length)setSelected(pages.data[0].id)},[pages.data,selected]);
 const refresh=()=>{qc.invalidateQueries({queryKey:['cms-pages']});qc.invalidateQueries({queryKey:['cms-page',selected]})};
 const choose=(value:string)=>{setMessage('');setSelected(value?Number(value):null)};
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const r=await api.post('/cms/pages',{...f,template:'standard'});setSelected(r.data.data.id);e.currentTarget.reset();refresh()};
 const add=async(type:string)=>{await api.post(`/cms/pages/${selected}/sections`,{type,content:{heading:'New section heading',...(type==='text'?{body:'Write your content here.'}:{text:'Write a short introduction here.'})},presentation:{background:'white',alignment:'left',spacing:'normal'},is_visible:true});refresh()};
 const remove=async(id:number)=>{await api.delete(`/cms/pages/${selected}/sections/${id}`);refresh()};
 const move=async(index:number,delta:number)=>{const ids=page.data.sections.map((s:any)=>s.id),next=index+delta;if(next<0||next>=ids.length)return;[ids[index],ids[next]]=[ids[next],ids[index]];await api.put(`/cms/pages/${selected}/sections-order`,{section_ids:ids});refresh()};
 const preview=async()=>{const r=await api.post(`/cms/pages/${selected}/preview`);window.open(r.data.preview_url,'_blank','noopener,noreferrer')};
 const publish=async()=>{await api.post(`/cms/pages/${selected}/publish`);setMessage('Page published successfully.');refresh()};
 if(pages.isError)return <section className="portal-guest"><h1>Power Admin access required.</h1><Link className="btn btn-primary" to="/sign-in">Sign in</Link></section>;
 return <section className="cms-editor"><aside><Link to="/staff" className="text-link"><ArrowLeft/> Practice dashboard</Link><h1>Website editor</h1><p>Create and update safe website pages without coding.</p><div className="cms-page-picker"><label htmlFor="existing-page">Choose an existing page</label><select id="existing-page" className="form-control" value={selected??''} onChange={e=>choose(e.target.value)} disabled={pages.isLoading||!pages.data?.length}><option value="">{pages.isLoading?'Loading pages…':pages.data?.length?'Select a page':'No existing pages'}</option>{pages.data?.map((p:any)=><option value={p.id} key={p.id}>{p.title} — /{p.slug} ({p.status})</option>)}</select><small>{pages.data?.length??0} page{pages.data?.length===1?'':'s'} available</small></div><details className="cms-create"><summary><FilePlus2/> Create a new page</summary><form onSubmit={create}><input className="form-control" name="title" placeholder="Page title" required/><input className="form-control" name="slug" placeholder="Page address, e.g. patient-guide" required/><button className="btn btn-primary"><FilePlus2/> Create page</button></form></details><nav aria-label="Existing website pages">{pages.data?.map((p:any)=><button type="button" className={selected===p.id?'active':''} onClick={()=>choose(String(p.id))} key={p.id}><span>{p.title}<small>/{p.slug} · {p.status}</small></span></button>)}</nav></aside><main>{!selected?<div className="cms-welcome"><FilePlus2/><h2>Choose a page to edit</h2><p>Use the existing-page dropdown or create a new page.</p></div>:page.isLoading?<div className="cms-welcome"><p>Opening page…</p></div>:page.data&&<><header><div><span className="eyebrow">Editing draft</span><h2>{page.data.title}</h2><p>Public address: /p/{page.data.slug}</p></div><div><button className="btn btn-outline-primary" onClick={preview}><Eye/> Preview</button><button className="btn btn-primary" onClick={publish}><Send/> Publish</button></div></header>{message&&<div className="success-line" role="status">{message}</div>}<div className="add-section"><span>Add section</span>{['hero','text','cta','stats','image_text'].map(t=><button type="button" onClick={()=>add(t)} key={t}><Plus/> {t.replace('_',' ')}</button>)}</div><div className="cms-canvas">{page.data.sections.map((s:any,i:number)=><SectionEditor key={s.id} section={s} pageId={selected} onSaved={refresh} onDelete={()=>remove(s.id)} onUp={()=>move(i,-1)} onDown={()=>move(i,1)}/>)}</div></>}</main></section>;
}

function SectionEditor({section,pageId,onSaved,onDelete,onUp,onDown}:{section:any;pageId:number;onSaved:()=>void;onDelete:()=>void;onUp:()=>void;onDown:()=>void}){const[heading,setHeading]=useState(section.content.heading||''),[text,setText]=useState(section.content.body||section.content.text||'');const save=async()=>{const textKey=section.type==='text'?'body':'text';await api.put(`/cms/pages/${pageId}/sections/${section.id}`,{type:section.type,content:{...section.content,heading,[textKey]:text},presentation:section.presentation||{},is_visible:section.is_visible});onSaved()};return <article className="cms-edit-section"><div className="section-tools"><span>{section.type.replace('_',' ')}</span><button onClick={onUp} aria-label="Move section up"><ArrowUp/></button><button onClick={onDown} aria-label="Move section down"><ArrowDown/></button><button onClick={onDelete} aria-label="Remove section"><Trash2/></button></div><label>Heading<input className="form-control" value={heading} onChange={e=>setHeading(e.target.value)}/></label>{section.type!=='stats'&&<label>Text<textarea className="form-control" value={text} onChange={e=>setText(e.target.value)}/></label>}<button className="btn btn-outline-primary" onClick={save}>Save section</button></article>}
