import { useQuery,useQueryClient } from '@tanstack/react-query';
import { ArrowRight,CalendarDays,Pencil,Save,X } from 'lucide-react';
import { useCallback,useContext,useEffect,useRef,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { api } from '../api';
import { CmsEditContext } from '../CmsEditContext';
import Seo from '../Seo';

type TextMark={type:'bold'|'italic'|'underline'|'link';start:number;end:number;url?:string};
type InlineTarget={sectionKey:string;field:string;label:string;value:string;marks:TextMark[]};

export default function CmsPublicPage({preview=false,slug,fallback,supplement}:{preview?:boolean;slug?:string;fallback?:React.ReactNode;supplement?:React.ReactNode}){
 const params=useParams(),qc=useQueryClient(),{editing,registerEditor}=useContext(CmsEditContext),editorRef=useRef<HTMLTextAreaElement>(null),[selected,setSelected]=useState<string|null>(null),[target,setTarget]=useState<InlineTarget|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[document,setDocument]=useState<any>(null),[lockVersion,setLockVersion]=useState(0),[history,setHistory]=useState<any[]>([]),[future,setFuture]=useState<any[]>([]),[saveState,setSaveState]=useState<'clean'|'unsaved'|'saving'|'saved'|'failed'>('clean');
 const pageSlug=slug??params.slug,endpoint=preview?`/cms/preview/${params.token}`:`/content/pages/${pageSlug}`;
 const page=useQuery({queryKey:['cms-public',endpoint],queryFn:async()=> (await api.get(endpoint)).data.data,retry:false});
 const pages=useQuery({queryKey:['cms-pages'],queryFn:async()=>(await api.get('/cms/pages')).data.data,enabled:editing&&!preview,retry:false});
 const editablePageId=pages.data?.find((item:any)=>item.slug===pageSlug)?.id;
 const draft=useQuery({queryKey:['cms-page',editablePageId],queryFn:async()=>(await api.get(`/cms/pages/${editablePageId}`)).data.data,enabled:Boolean(editing&&editablePageId),retry:false});
 useEffect(()=>{if(!draft.data)return;setDocument(draft.data);setLockVersion(draft.data.lock_version);setHistory([]);setFuture([]);setSaveState('clean');setSelected(null);setError('')},[draft.data?.id]);
 const changeDocument=useCallback((change:(current:any)=>any)=>{setDocument((current:any)=>{if(!current)return current;const next=change(current);setHistory(items=>[...items,current].slice(-50));setFuture([]);setSaveState('unsaved');return next})},[]);
 const undo=useCallback(()=>{setHistory(items=>{if(!items.length)return items;const previous=items[items.length-1];setDocument((current:any)=>{if(current)setFuture(next=>[current,...next]);return previous});setSaveState('unsaved');return items.slice(0,-1)})},[]);
 const redo=useCallback(()=>{setFuture(items=>{if(!items.length)return items;const next=items[0];setDocument((current:any)=>{if(current)setHistory(previous=>[...previous,current].slice(-50));return next});setSaveState('unsaved');return items.slice(1)})},[]);
 const save=useCallback(async()=>{if(!editablePageId||!document)return;setError('');setSaveState('saving');try{const response=await api.put(`/cms/pages/${editablePageId}/visual-draft`,{lock_version:lockVersion,sections:document.sections});setDocument(response.data.data);setLockVersion(response.data.data.lock_version);setSaveState('saved');setMessage('The complete page draft is saved privately.');qc.setQueryData(['cms-page',editablePageId],response.data.data)}catch(e:any){setSaveState('failed');setError(e?.response?.data?.message||'The draft could not be saved. Your edits are still in this browser; retry Save Draft.')}},[document,editablePageId,lockVersion,qc]);
 const previewDraft=useCallback(async()=>{if(!editablePageId||!document)return;setError('');try{const response=await api.post(`/cms/pages/${editablePageId}/preview`,{lock_version:lockVersion,sections:document.sections});window.open(response.data.preview_url,'_blank','noopener,noreferrer')}catch(e:any){setError(e?.response?.data?.message||'The exact current draft preview could not be opened.')}},[document,editablePageId,lockVersion]);
 const publish=useCallback(async()=>{if(!editablePageId||!document||!window.confirm('Publish this exact page for all website visitors?'))return;setError('');setSaveState('saving');try{const response=await api.post(`/cms/pages/${editablePageId}/publish`,{lock_version:lockVersion,sections:document.sections});setDocument(response.data.data);setLockVersion(response.data.data.lock_version);setSaveState('saved');setMessage('Published successfully. Logged-out visitors now see this exact version.');qc.setQueryData(['cms-page',editablePageId],response.data.data);await qc.invalidateQueries({queryKey:['cms-public',endpoint]})}catch(e:any){setSaveState('failed');setError(e?.response?.data?.message||'Publishing failed. Nothing new was made public and your edits are retained.')}},[document,editablePageId,endpoint,lockVersion,qc]);
 const addSection=useCallback(()=>{changeDocument(current=>({...current,sections:[...current.sections,{id:null,section_key:crypto.randomUUID(),type:'text',sort_order:current.sections.length,is_visible:true,content:{heading:'New section',body:'Double-click this text to edit it.'},presentation:{background:'white',alignment:'left',spacing:'normal'}}]}));setMessage('A Rich Text section was added to this page. Use Save Draft when ready.')},[changeDocument]);
 const saveInline=()=>{if(!target)return;changeDocument(current=>({...current,sections:current.sections.map((section:any)=>section.section_key===target.sectionKey?{...section,content:{...section.content,[target.field]:target.value,[`${target.field}_marks`]:target.marks}}:section)}));setMessage(`${target.label} updated on the page. Save Draft when ready.`);setTarget(null)};
 const addMark=(type:TextMark['type'])=>{if(!target||!editorRef.current)return;const start=editorRef.current.selectionStart,end=editorRef.current.selectionEnd;if(start===end){setError('Select some text first.');return}const url=type==='link'?window.prompt('Safe internal path or HTTP(S) link','/')||'':'';if(type==='link'&&!url)return;const mark:TextMark={type,start,end,...(url?{url}:{})},marks=[...target.marks,mark].sort((a,b)=>a.start-b.start);if(marks.some((item,index)=>index>0&&item.start<marks[index-1].end)){setError('Formatting ranges cannot overlap. Remove the existing range first.');return}setError('');setTarget({...target,marks})};
 const displayed=editing&&document?document:page.data;
 useEffect(()=>{if(!editing||!document){registerEditor(null);return}registerEditor({pageTitle:document.title||'Website page',selection:selected?`Page > Section: ${document.sections.find((section:any)=>section.section_key===selected)?.type||'section'}`:'Page',saveState,canUndo:history.length>0,canRedo:future.length>0,select:()=>{setSelected(null);setMessage('Select a section or double-click its visible text.')},addSection,undo,redo,preview:previewDraft,save,publish});return()=>registerEditor(null)},[addSection,document,editing,future.length,history.length,previewDraft,publish,redo,registerEditor,save,saveState,selected,undo]);
 useEffect(()=>{if(!editing||!['unsaved','failed'].includes(saveState))return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[editing,saveState]);
 useEffect(()=>{if(!editing)return;const shortcut=(event:KeyboardEvent)=>{if(!(event.ctrlKey||event.metaKey))return;if(event.key.toLowerCase()==='s'){event.preventDefault();void save()}else if(event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo()}};window.document.addEventListener('keydown',shortcut);return()=>window.document.removeEventListener('keydown',shortcut)},[editing,redo,save,undo]);
 if(page.isLoading&&!(editing&&draft.data))return fallback??<div className="portal-loading">Opening page…</div>;
 if(page.isError&&!(editing&&draft.data))return editing&&draft.isLoading?<div className="portal-loading">Opening private draft…</div>:fallback??<section className="portal-guest"><h1>This page is not available.</h1><Link className="btn btn-primary" to="/">Return home</Link></section>;
 if(!displayed)return <div className="portal-loading">Opening page…</div>;
 return <article className={`${preview?'cms-preview':''} ${editing?'cms-live-editing':''}`}><Seo title={displayed.seo?.title||displayed.title||'Practice information'} description={displayed.seo?.description||'Specialist breast oncology care, academic work and patient education in Ile-Ife, Nigeria.'} canonicalPath={pageSlug==='home'?'/':pageSlug&&['about','services','research'].includes(pageSlug)?`/${pageSlug}`:`/p/${pageSlug}` } noIndex={preview}/>{preview&&<div className="preview-banner">Draft preview · This is not public</div>}{editing&&<div className="cms-edit-banner" role="status"><Pencil/> Edit Mode is on. Changes happen on this real page and remain private until Publish.</div>}{message&&<div className="cms-inline-status" role="status">{message}</div>}{error&&<div className="cms-inline-error" role="alert">{error}</div>}{displayed.sections.filter((section:any)=>editing||section.is_visible).map((section:any)=><Section section={section} editing={editing} selected={selected===section.section_key} onSelect={()=>editing&&setSelected(section.section_key)} onEdit={(field,label,value,marks)=>setTarget({sectionKey:section.section_key,field,label,value,marks})} key={section.section_key}/>)}{supplement}{target&&<div className="cms-inline-dialog" role="dialog" aria-modal="true" aria-labelledby="inline-edit-title"><div><button type="button" className="cms-inline-close" aria-label="Close inline editor" onClick={()=>setTarget(null)}><X/></button><span className="eyebrow">Private draft</span><h2 id="inline-edit-title">Edit {target.label.toLowerCase()}</h2><label>{target.label}<textarea ref={editorRef} className="form-control" autoFocus value={target.value} onChange={e=>setTarget({...target,value:e.target.value,marks:[]})}/></label><div className="cms-mark-tools" aria-label="Selected text formatting"><button type="button" onClick={()=>addMark('bold')}><b>B</b> Bold</button><button type="button" onClick={()=>addMark('italic')}><i>I</i> Italic</button><button type="button" onClick={()=>addMark('underline')}><u>U</u> Underline</button><button type="button" onClick={()=>addMark('link')}>Link</button></div>{target.marks.length>0&&<ul className="cms-mark-list">{target.marks.map((mark,index)=><li key={`${mark.type}-${mark.start}-${mark.end}`}>{mark.type}: “{target.value.slice(mark.start,mark.end)}” <button type="button" onClick={()=>setTarget({...target,marks:target.marks.filter((_,i)=>i!==index)})}>Remove</button></li>)}</ul>}<p>This change is applied to the structured page draft and is not public until Publish.</p><div><button type="button" className="btn btn-outline-primary" onClick={()=>setTarget(null)}>Cancel</button><button type="button" className="btn btn-primary" onClick={saveInline}><Save/> Apply to draft</button></div></div></div>}</article>
}

function EditableText({tag,field,label,value,marks=[],editing,onEdit}:{tag:string;field:string;label:string;value?:string;marks?:TextMark[];editing:boolean;onEdit:(field:string,label:string,value:string,marks:TextMark[])=>void}){if(!value)return null;const Tag=tag as any;return <Tag className={editing?'cms-editable-text':undefined} title={editing?'Double-click to edit':undefined} onDoubleClick={(event:any)=>{if(!editing)return;event.stopPropagation();onEdit(field,label,value,marks)}}><MarkedText value={value} marks={marks}/></Tag>}

function MarkedText({value,marks=[]}:{value:string;marks?:TextMark[]}){const parts:React.ReactNode[]=[];let cursor=0;marks.forEach((mark,index)=>{if(mark.start>cursor)parts.push(value.slice(cursor,mark.start));const text=value.slice(mark.start,mark.end),key=`${mark.type}-${index}`;parts.push(mark.type==='bold'?<strong key={key}>{text}</strong>:mark.type==='italic'?<em key={key}>{text}</em>:mark.type==='underline'?<u key={key}>{text}</u>:mark.url?.startsWith('/')?<Link to={mark.url} key={key}>{text}</Link>:<a href={mark.url} rel="noopener noreferrer" key={key}>{text}</a>);cursor=mark.end});if(cursor<value.length)parts.push(value.slice(cursor));return <>{parts}</>}

function Section({section,editing,selected,onSelect,onEdit}:{section:any;editing:boolean;selected:boolean;onSelect:()=>void;onEdit:(field:string,label:string,value:string,marks:TextMark[])=>void}){
 const c=section.content,p=section.presentation||{},cls=`cms-section cms-${section.type} cms-bg-${p.background||'ivory'} cms-align-${p.alignment||'left'} cms-space-${p.spacing||'normal'} cms-font-${p.font_family||'site'} cms-size-${p.font_size||'normal'} cms-weight-${p.font_weight||'regular'} cms-emphasis-${p.emphasis||'none'} cms-color-${p.text_color||'default'} cms-leading-${p.line_height||'normal'} ${editing?'cms-editable-section':''} ${selected?'selected':''} ${!section.is_visible?'cms-hidden-draft':''}`,inner=`container cms-width-${p.width||'normal'}`;
 const eyebrow=<EditableText tag="span" field="eyebrow" label="Eyebrow text" value={c.eyebrow} marks={c.eyebrow_marks} editing={editing} onEdit={onEdit}/>,heading=(level='h2')=><EditableText tag={level} field="heading" label="Heading" value={c.heading} marks={c.heading_marks} editing={editing} onEdit={onEdit}/>;
 if(section.type==='hero')return <section className={cls} onClick={onSelect}>{editing&&<EditTag/>}<div className={inner}>{eyebrow}{heading('h1')}<EditableText tag="p" field="text" label="Supporting text" value={c.text} marks={c.text_marks} editing={editing} onEdit={onEdit}/><div className="hero-actions">{c.primary_label&&<SafeLink label={c.primary_label} url={c.primary_url} style={c.primary_style} icon={c.primary_icon} visibility={c.primary_visibility}/>} {c.secondary_label&&<SafeLink label={c.secondary_label} url={c.secondary_url} style={c.secondary_style||'outline'} icon={c.secondary_icon} visibility={c.secondary_visibility}/>}</div></div></section>;
 if(section.type==='cta')return <section className={cls} onClick={onSelect}>{editing&&<EditTag/>}<div className={inner}>{eyebrow}{heading()}<EditableText tag="p" field="text" label="Supporting text" value={c.text} marks={c.text_marks} editing={editing} onEdit={onEdit}/>{c.button_label&&<SafeLink label={c.button_label} url={c.button_url} style={c.button_style} icon={c.button_icon} visibility={c.button_visibility}/>}</div></section>;
 if(section.type==='stats')return <section className={cls} onClick={onSelect}>{editing&&<EditTag/>}<div className={inner}>{eyebrow}{heading()}<EditableText tag="p" field="text" label="Supporting text" value={c.text} marks={c.text_marks} editing={editing} onEdit={onEdit}/><div className="cms-stats">{c.items?.map((item:any,i:number)=><div key={i}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div></div></section>;
 if(section.type==='image_text')return <section className={cls} onClick={onSelect}>{editing&&<EditTag/>}<div className={`${inner} cms-image-grid cms-image-${p.image_alignment||'left'} cms-image-width-${p.image_width||'medium'}`}>{c.image_url&&<SafeImage content={c} presentation={p}/>}<div>{eyebrow}{heading()}<EditableText tag="p" field="text" label="Supporting text" value={c.text} marks={c.text_marks} editing={editing} onEdit={onEdit}/></div></div></section>;
 return <section className={cls} onClick={onSelect}>{editing&&<EditTag/>}<div className={inner}>{eyebrow}{heading()}<EditableText tag="p" field="body" label="Body text" value={c.body} marks={c.body_marks} editing={editing} onEdit={onEdit}/></div></section>
}

function EditTag(){return <span className="cms-edit-tag"><Pencil/> Select · double-click text</span>}
function SafeImage({content,presentation}:{content:any;presentation:any}){const image=<img className={`cms-radius-${presentation.image_radius||'soft'} cms-fit-${presentation.image_fit||'cover'} cms-crop-${presentation.crop_position||'center'}`} src={content.image_url} alt={content.image_alt||''}/>;if(!content.image_link)return image;return content.image_link.startsWith('/')?<Link to={content.image_link}>{image}</Link>:<a href={content.image_link} rel="noopener noreferrer">{image}</a>}
function SafeLink({label,url='/',style='primary',icon='arrow',visibility='show'}:{label:string;url?:string;style?:string;icon?:string;visibility?:string}){if(visibility==='hide')return null;const cls=style==='outline'?'btn btn-outline-primary':style==='light'?'btn btn-light':'btn btn-primary',symbol=icon==='none'?null:icon==='calendar'?<CalendarDays/>:<ArrowRight/>;return url.startsWith('/')?<Link className={cls} to={url}>{label}{symbol}</Link>:<a className={cls} href={url} rel="noopener noreferrer">{label}{symbol}</a>}
