import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Camera, CheckCircle2, Clock3, LogOut, ShieldCheck, Video } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { api } from '../api';

export default function ConsultationsPage(){
 const qc=useQueryClient(),[selected,setSelected]=useState<any>(null),[room,setRoom]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const list=useQuery({queryKey:['my-consultations'],queryFn:async()=>(await api.get('/me/consultations')).data.data,retry:false});
 const message=(e:any,fallback:string)=>e?.response?.data?.message||fallback;
 const open=async(id:number)=>{setBusy(`open-${id}`);setError('');setRoom(null);try{setSelected((await api.get(`/consultations/${id}`)).data)}catch(e){setError(message(e,'The consultation details could not be loaded. Try again.'))}finally{setBusy('')}};
 const consent=async()=>{setBusy('consent');setError('');try{await api.post(`/consultations/${selected.data.id}/consent`,{accepted:true});await open(selected.data.id)}catch(e){setError(message(e,'Your consent could not be recorded. Review the statement and try again.'))}finally{setBusy('')}};
 const wait=async()=>{setBusy('wait');setError('');try{await api.post(`/consultations/${selected.data.id}/waiting-room`);await open(selected.data.id)}catch(e){setError(message(e,'The waiting room is not available yet.'))}finally{setBusy('')}};
 const join=async()=>{setBusy('join');setError('');try{const auth=(await api.post(`/consultations/${selected.data.id}/join-authorization`)).data;setRoom((await api.get(auth.join_url)).data)}catch(e){setError(message(e,'Please wait for the practice team to admit you.'))}finally{setBusy('')}};
 const leave=async()=>{setBusy('leave');setError('');try{await api.post(`/consultations/${selected.data.id}/leave`);setRoom(null);await qc.invalidateQueries({queryKey:['my-consultations']})}catch(e){setError(message(e,'The consultation could not be closed. Check your connection and try again.'))}finally{setBusy('')}};
 if(list.isError)return <section className="portal-guest"><h1>Please sign in as a patient.</h1><Link className="btn btn-primary" to="/sign-in">Sign in</Link></section>;
 if(list.isLoading)return <div className="portal-loading" role="status">Loading online consultations…</div>;
 return <section className="portal"><div className="container narrow"><span className="eyebrow">Patient portal</span><h1 className="settings-title">Online consultations</h1><p className="section-help">Your secure waiting room opens 30 minutes before the confirmed appointment.</p>{error&&<div className="alert alert-danger" role="alert">{error}</div>}
  {!list.data?.length?<div className="empty-state"><Video/><h3>No online consultations scheduled</h3><p>Confirmed online appointments will appear here.</p></div>:<div className="consultation-list">{list.data.map((c:any)=><button disabled={busy===`open-${c.id}`} key={c.id} onClick={()=>open(c.id)}><Video/><span><b>{c.appointment.service.name}</b><small>{new Date(c.appointment.starts_at).toLocaleString('en-NG',{dateStyle:'long',timeStyle:'short'})}</small></span><em>{c.status}</em></button>)}</div>}
  {selected&&<div className="waiting-room"><div className="waiting-video"><Camera/><h2>{room?'Consultation room':'Private waiting room'}</h2><p>{room?.configuration.message||'Your camera and microphone are not activated until a configured video provider is ready.'}</p></div><div className="waiting-details"><ShieldCheck/><h3>{selected.data.appointment.service.name}</h3><p><Clock3/> {new Date(selected.data.appointment.starts_at).toLocaleString('en-NG')}</p>{!selected.has_consent?<><p>Before entering, confirm that you consent to a remote consultation and understand that urgent concerns should use local emergency services.</p><button disabled={busy==='consent'} className="btn btn-primary" onClick={consent}><CheckCircle2/> {busy==='consent'?'Saving consent…':'I understand and consent'}</button></>:room?<button disabled={busy==='leave'} className="btn btn-outline-primary" onClick={leave}><LogOut/> {busy==='leave'?'Leaving…':'Leave consultation'}</button>:<><button disabled={busy==='wait'} className="btn btn-primary" onClick={wait}>{busy==='wait'?'Entering…':'Enter waiting room'}</button>{['ready','in_progress'].includes(selected.data.status)&&<button disabled={busy==='join'} className="btn btn-outline-primary" onClick={join}>{busy==='join'?'Joining…':'Join consultation'}</button>}</>}</div></div>}
  <Link className="text-link mt-4" to="/portal">Back to patient portal</Link>
 </div></section>
}
