import { useQuery,useQueryClient } from '@tanstack/react-query';
import { ArrowLeft,Search,ShieldCheck,UserPlus,Users } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';

const message=(error:any,fallback:string)=>error?.response?.data?.message||Object.values(error?.response?.data?.errors??{}).flat()[0]||fallback;
type Account={id:number;name:string;email:string;phone?:string;role:string;is_active:boolean;email_verified_at?:string;account_claimed_at?:string};

export default function StaffAccountsPage(){
 const qc=useQueryClient();
 const [query,setQuery]=useState(''),[role,setRole]=useState(''),[active,setActive]=useState(''),[page,setPage]=useState(1),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[editing,setEditing]=useState<Account|null>(null);
 const dashboard=useQuery({queryKey:['staff-dashboard'],queryFn:async()=>(await api.get('/staff/dashboard')).data,retry:false});
 const accounts=useQuery({queryKey:['staff-accounts',query,role,active,page],queryFn:async()=>(await api.get('/staff/accounts',{params:{q:query||undefined,role:role||undefined,active:active===''?undefined:active==='true',page}})).data,retry:false});
 const power=dashboard.data?.role==='power_admin';
 const run=async(key:string,action:()=>Promise<any>,success:string)=>{setBusy(key);setError('');setNotice('');try{const response=await action();setNotice(success);await qc.invalidateQueries({queryKey:['staff-accounts']});return response}catch(e){setError(String(message(e,'The account change was not completed. Your entries are still here so you can try again.')))}finally{setBusy('')}};
 if(dashboard.isError||accounts.isError)return <section className="portal-guest"><h1>Account administration access required.</h1><Link className="btn btn-primary" to="/sign-in">Sign in</Link></section>;
 return <main className="staff-main management-page"><header><div><span className="eyebrow">Identity & access</span><h1>Accounts</h1><p>{power?'Manage patients and staff without weakening the Power Admin safeguards.':'Manage patient invitations, contact details and active access.'}</p></div><Link className="btn btn-outline-primary" to="/staff"><ArrowLeft/> Dashboard</Link></header>{notice&&<div className="success-line" role="status">{notice}</div>}{error&&<div className="alert alert-danger" role="alert">{error}</div>}<div className="management-grid account-management-grid"><section className="staff-card"><div className="card-heading"><div><span className="eyebrow">Directory</span><h2>Practice accounts</h2></div><Users/></div><div className="account-filters"><label><span>Search accounts</span><div><Search/><input className="form-control" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Name, email or phone"/></div></label>{power&&<label>Filter by role<select className="form-control" value={role} onChange={e=>{setRole(e.target.value);setPage(1)}}><option value="">All roles</option><option value="patient">Patient</option><option value="moderator">Moderator</option><option value="admin">Admin</option><option value="power_admin">Power Admin</option></select></label>}<label>Status<select className="form-control" value={active} onChange={e=>{setActive(e.target.value);setPage(1)}}><option value="">All</option><option value="true">Active</option><option value="false">Inactive</option></select></label></div>{accounts.isLoading?<p role="status">Loading accounts…</p>:accounts.data?.data?.length?accounts.data.data.map((account:Account)=><article className="account-row" key={account.id}><div className="patient-avatar">{account.name.slice(0,1)}</div><div><h3>{account.name}</h3><p>{account.email}{account.phone?` · ${account.phone}`:''}</p><small>{account.role.replace('_',' ')} · {account.is_active?'active':'inactive'} · {account.account_claimed_at?'claimed':'invited'}</small></div><button className="btn btn-outline-primary" onClick={()=>setEditing(account)}>Edit</button></article>):<div className="staff-empty"><Users/><p>No accounts match these filters.</p></div>}<div className="pagination-actions"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {accounts.data?.current_page??page} of {accounts.data?.last_page??1}</span><button disabled={page>=(accounts.data?.last_page??1)} onClick={()=>setPage(value=>value+1)}>Next</button></div></section><InviteAccount power={power} busy={busy} run={run}/></div>{editing&&<EditAccount account={editing} power={power} busy={busy} onClose={()=>setEditing(null)} run={run}/>}</main>;
}

function InviteAccount({power,busy,run}:{power:boolean;busy:string;run:(key:string,action:()=>Promise<any>,success:string)=>Promise<any>}){const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[role,setRole]=useState('patient'),[password,setPassword]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();const result=await run('invite',()=>api.post('/staff/accounts',{name,email,phone,role,current_password:password||undefined}),'Account invitation created.');if(result){setName('');setEmail('');setPhone('');setRole('patient');setPassword('')}};return <section className="staff-card"><div className="card-heading"><div><span className="eyebrow">New access</span><h2>Invite an account</h2></div><UserPlus/></div><form className="management-form" onSubmit={submit}><label>Full name<input required className="form-control" value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required type="email" className="form-control" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input className="form-control" value={phone} onChange={e=>setPhone(e.target.value)}/></label>{power&&<label>Invite role<select className="form-control" value={role} onChange={e=>setRole(e.target.value)}><option value="patient">Patient</option><option value="moderator">Moderator</option><option value="admin">Admin</option><option value="power_admin">Power Admin</option></select></label>}{power&&role!=='patient'&&<label>Confirm with your password<input required type="password" autoComplete="current-password" className="form-control" value={password} onChange={e=>setPassword(e.target.value)}/></label>}<p className="section-help">The new user receives a time-limited password claim link. Email verification remains a separate security step.</p><button disabled={busy==='invite'} className="btn btn-primary">{busy==='invite'?'Creating…':'Create invitation'}</button></form></section>}

function EditAccount({account,power,busy,onClose,run}:{account:Account;power:boolean;busy:string;onClose:()=>void;run:(key:string,action:()=>Promise<any>,success:string)=>Promise<any>}){const [name,setName]=useState(account.name),[email,setEmail]=useState(account.email),[phone,setPhone]=useState(account.phone??''),[role,setRole]=useState(account.role),[active,setActive]=useState(account.is_active),[password,setPassword]=useState('');const sensitive=role!==account.role||active!==account.is_active;const save=async(e:React.FormEvent)=>{e.preventDefault();const result=await run(`edit-${account.id}`,()=>api.patch(`/staff/accounts/${account.id}`,{name,email,phone,role:power?role:undefined,is_active:active,current_password:sensitive?password:undefined}),'Account updated.');if(result)onClose()};return <div className="calendar-dialog" role="dialog" aria-modal="true" aria-labelledby="edit-account-title"><form onSubmit={save}><button type="button" className="dialog-close" aria-label="Close account editor" onClick={onClose}>×</button><ShieldCheck/><h2 id="edit-account-title">Edit {account.name}</h2><label>Full name<input required className="form-control" value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required type="email" className="form-control" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input className="form-control" value={phone} onChange={e=>setPhone(e.target.value)}/></label>{power&&<label>Account role<select className="form-control" value={role} onChange={e=>setRole(e.target.value)}><option value="patient">Patient</option><option value="moderator">Moderator</option><option value="admin">Admin</option><option value="power_admin">Power Admin</option></select></label>}<label className="account-active"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Account is active</label>{sensitive&&<label>Confirm with your password<input required type="password" autoComplete="current-password" className="form-control" value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button disabled={busy===`edit-${account.id}`} className="btn btn-primary">{busy===`edit-${account.id}`?'Saving…':'Save account'}</button></form></div>}
