<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::table('publications',function(Blueprint $t){$t->text('abstract')->nullable();$t->json('keywords')->nullable();$t->string('publication_type')->default('journal_article');});
 Schema::table('research_claims',function(Blueprint $t){$t->string('target_type')->nullable();$t->json('target_payload')->nullable();});
 Schema::create('career_entries',function(Blueprint $t){$t->id();$t->string('year_label');$t->string('institution');$t->string('position');$t->string('location')->nullable();$t->text('description')->nullable();$t->string('source_url');$t->string('verification_status')->default('pending_review')->index();$t->boolean('is_published')->default(false);$t->unsignedSmallInteger('sort_order')->default(0);$t->timestamps();});
 Schema::create('achievements',function(Blueprint $t){$t->id();$t->string('title');$t->string('year_label')->nullable();$t->string('organization')->nullable();$t->text('description')->nullable();$t->string('category');$t->string('source_url');$t->string('verification_status')->default('pending_review')->index();$t->boolean('is_published')->default(false);$t->timestamps();});
 Schema::create('education_articles',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->text('summary');$t->text('content');$t->string('author');$t->string('medical_reviewer');$t->date('reviewed_at');$t->date('content_updated_at');$t->string('category');$t->json('tags')->nullable();$t->text('medical_disclaimer');$t->string('status')->default('draft')->index();$t->timestamp('published_at')->nullable();$t->timestamps();});
 Schema::create('practice_contacts',function(Blueprint $t){$t->id();$t->string('label');$t->string('type');$t->string('value');$t->boolean('is_public')->default(false);$t->unsignedSmallInteger('sort_order')->default(0);$t->timestamps();});
 }public function down():void{Schema::dropIfExists('practice_contacts');Schema::dropIfExists('education_articles');Schema::dropIfExists('achievements');Schema::dropIfExists('career_entries');Schema::table('research_claims',fn(Blueprint $t)=>$t->dropColumn(['target_type','target_payload']));Schema::table('publications',fn(Blueprint $t)=>$t->dropColumn(['abstract','keywords','publication_type']));}};
